/**
 *  xEngine - C++ Game Engine Library
 *  Copyright (C) 2023  Julian Zampiccoli
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License along
 *  with this program; if not, write to the Free Software Foundation, Inc.,
 *  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#include "xng/render/graph/passes/deferredlightingpass.hpp"

#include "xng/render/graph/framegraphbuilder.hpp"

#include "xng/render/graph/passes/constructionpass.hpp"
#include "xng/render/graph/framegraphsettings.hpp"

#include "xng/render/geometry/vertexstream.hpp"

#include "graph/deferredlightingpass_vs.hpp" // Generated by cmake
#include "graph/deferredlightingpass_fs.hpp" // Generated by cmake

namespace xng {
#pragma pack(push, 1)
    struct PointLightData {
        std::array<float, 4> position;
        std::array<float, 4> color;
        std::array<float, 4> farPlane;
    };

    struct ShaderStorageData {
        std::array<float, 4> viewPosition{};
        std::array<int, 4> enableShadows{};
    };
#pragma pack(pop)

    static std::pair<std::vector<PointLightData>, std::vector<PointLightData>> getPointLights(const Scene &scene) {
        std::vector<PointLightData> pointLights;
        std::vector<PointLightData> shadowLights;
        for (auto &node: scene.rootNode.findAll({typeid(PointLightProperty)})) {
            auto l = node.getProperty<PointLightProperty>().light;
            auto t = node.getProperty<TransformProperty>().transform;
            auto v = l.color.divide();
            auto tmp = PointLightData{
                    .position =  Vec4f(t.getPosition().x,
                                       t.getPosition().y,
                                       t.getPosition().z,
                                       0).getMemory(),
                    .color = Vec4f(v.x * l.power, v.y * l.power, v.z * l.power, 1).getMemory(),
                    .farPlane = Vec4f(l.shadowFarPlane, 0, 0, 0).getMemory()
            };
            if (l.castShadows)
                shadowLights.emplace_back(tmp);
            else
                pointLights.emplace_back(tmp);
        }
        return {pointLights, shadowLights};
    }

    DeferredLightingPass::DeferredLightingPass() = default;

    void DeferredLightingPass::setup(FrameGraphBuilder &builder) {
        scene = builder.getScene();

        if (!vertexBufferRes.assigned) {
            VertexBufferDesc desc;
            desc.size = mesh.vertices.size() * mesh.vertexLayout.getSize();
            vertexBufferRes = builder.createVertexBuffer(desc);

            VertexArrayObjectDesc oDesc;
            oDesc.vertexLayout = mesh.vertexLayout;
            vertexArrayObjectRes = builder.createVertexArrayObject(oDesc);

            builder.write(vertexBufferRes);
        }

        builder.persist(vertexBufferRes);
        builder.persist(vertexArrayObjectRes);
        builder.read(vertexBufferRes);
        builder.read(vertexArrayObjectRes);

        if (!pipelineRes.assigned) {
            pipelineRes = builder.createPipeline(RenderPipelineDesc{
                    .shaders = {
                            {VERTEX,   deferredlightingpass_vs},
                            {FRAGMENT, deferredlightingpass_fs}
                    },
                    .bindings = {BIND_SHADER_STORAGE_BUFFER,
                                 BIND_TEXTURE_BUFFER,
                                 BIND_TEXTURE_BUFFER,
                                 BIND_TEXTURE_BUFFER,
                                 BIND_TEXTURE_BUFFER,
                                 BIND_TEXTURE_BUFFER,
                                 BIND_TEXTURE_BUFFER,
                                 BIND_TEXTURE_ARRAY_BUFFER,
                                 BIND_SHADER_STORAGE_BUFFER,
                                 BIND_SHADER_STORAGE_BUFFER,
                    },
                    .primitive = TRIANGLES,
                    .vertexLayout = mesh.vertexLayout,
                    .enableDepthTest = true,
                    .depthTestWrite = true,
            });
        }

        builder.persist(pipelineRes);
        builder.read(pipelineRes);

        renderSize = builder.getBackBufferDescription().size
                     * builder.getSettings().get<float>(FrameGraphSettings::SETTING_RENDER_SCALE);

        targetRes = builder.createRenderTarget(RenderTargetDesc{
                .size = renderSize,
                .numberOfColorAttachments = 1,
                .hasDepthStencilAttachment = true
        });
        builder.read(targetRes);

        colorTextureRes = builder.getSlot(SLOT_DEFERRED_COLOR);
        builder.write(colorTextureRes);

        depthTextureRes = builder.getSlot(SLOT_DEFERRED_DEPTH);
        builder.write(depthTextureRes);

        passRes = builder.createRenderPass(RenderPassDesc{
                .numberOfColorAttachments = 1,
                .hasDepthStencilAttachment = true});

        builder.read(passRes);

        auto pointLightNodes = scene.rootNode.findAll({typeid(PointLightProperty)});

        size_t pointLights = 0;
        size_t shadowPointLights = 0;

        for (auto l: pointLightNodes) {
            if (l.getProperty<PointLightProperty>().light.castShadows)
                shadowPointLights++;
            else
                pointLights++;
        }

        shaderDataBufferRes = builder.createShaderStorageBuffer(
                ShaderStorageBufferDesc{.size =  sizeof(ShaderStorageData)});
        builder.read(shaderDataBufferRes);
        builder.write(shaderDataBufferRes);

        pointLightBufferRes = builder.createShaderStorageBuffer(ShaderStorageBufferDesc{
                .size = sizeof(PointLightData) * pointLights
        });
        builder.read(pointLightBufferRes);
        builder.write(pointLightBufferRes);

        shadowPointLightBufferRes = builder.createShaderStorageBuffer(ShaderStorageBufferDesc{
                .size = sizeof(PointLightData) * shadowPointLights
        });
        builder.read(shadowPointLightBufferRes);
        builder.write(shadowPointLightBufferRes);

        gBufferPosition = builder.getSlot(SLOT_GBUFFER_POSITION);
        builder.read(gBufferPosition);

        gBufferNormal = builder.getSlot(SLOT_GBUFFER_NORMAL);
        builder.read(gBufferNormal);

        gBufferTangent = builder.getSlot(SLOT_GBUFFER_TANGENT);
        builder.read(gBufferTangent);

        gBufferRoughnessMetallicAO = builder.getSlot(SLOT_GBUFFER_ROUGHNESS_METALLIC_AO);
        builder.read(gBufferRoughnessMetallicAO);

        gBufferAlbedo = builder.getSlot(SLOT_GBUFFER_ALBEDO);
        builder.read(gBufferAlbedo);

        gBufferModelObject = builder.getSlot(SLOT_GBUFFER_OBJECT_SHADOWS);
        builder.read(gBufferModelObject);

        gBufferDepth = builder.getSlot(SLOT_GBUFFER_DEPTH);
        builder.read(gBufferDepth);

        cameraTransform = builder.getScene().rootNode.find<CameraProperty>()
                .getProperty<TransformProperty>().transform;

        commandBuffer = builder.createCommandBuffer();
        builder.write(commandBuffer);

        this->scene = builder.getScene();

        if (builder.checkSlot(SLOT_SHADOW_MAP_POINT)) {
            pointLightShadowMapRes = builder.getSlot(FrameGraphSlot::SLOT_SHADOW_MAP_POINT);
            builder.read(pointLightShadowMapRes);
        } else {
            pointLightShadowMapRes = {};
        }

        pointLightShadowMapDefaultRes = builder.createTextureArrayBuffer({});
        builder.read(pointLightShadowMapDefaultRes);
    }

    void DeferredLightingPass::execute(FrameGraphPassResources &resources,
                                       const std::vector<std::reference_wrapper<CommandQueue>> &renderQueues,
                                       const std::vector<std::reference_wrapper<CommandQueue>> &computeQueues,
                                       const std::vector<std::reference_wrapper<CommandQueue>> &transferQueues) {
        auto &target = resources.get<RenderTarget>(targetRes);

        auto &pipeline = resources.get<RenderPipeline>(pipelineRes);
        auto &pass = resources.get<RenderPass>(passRes);

        auto &vertexBuffer = resources.get<VertexBuffer>(vertexBufferRes);
        auto &vertexArrayObject = resources.get<VertexArrayObject>(vertexArrayObjectRes);

        auto &uniformBuffer = resources.get<ShaderStorageBuffer>(shaderDataBufferRes);

        auto &pointLightBuffer = resources.get<ShaderStorageBuffer>(pointLightBufferRes);
        auto &shadowPointLightBuffer = resources.get<ShaderStorageBuffer>(shadowPointLightBufferRes);

        auto &colorTex = resources.get<TextureBuffer>(colorTextureRes);
        auto &depthTex = resources.get<TextureBuffer>(depthTextureRes);

        auto &cBuffer = resources.get<CommandBuffer>(commandBuffer);

        auto &pointLightShadowMap = pointLightShadowMapRes.assigned ? resources.get<TextureArrayBuffer>(
                pointLightShadowMapRes) : resources.get<TextureArrayBuffer>(pointLightShadowMapDefaultRes);

        auto pointLights = getPointLights(scene);

        pointLightBuffer.upload(reinterpret_cast<const uint8_t *>(pointLights.first.data()),
                                pointLights.first.size() * sizeof(PointLightData));
        shadowPointLightBuffer.upload(reinterpret_cast<const uint8_t *>(pointLights.second.data()),
                                      pointLights.second.size() * sizeof(PointLightData));

        if (!quadAllocated) {
            quadAllocated = true;
            auto verts = VertexStream().addVertices(mesh.vertices).getVertexBuffer();
            vertexBuffer.upload(0,
                                verts.data(),
                                verts.size());
            vertexArrayObject.setBuffers(vertexBuffer);
        }

        ShaderStorageData buf;
        buf.viewPosition = Vec4f(cameraTransform.getPosition().x,
                                 cameraTransform.getPosition().y,
                                 cameraTransform.getPosition().z,
                                 0).getMemory();
        buf.enableShadows.at(0) = pointLightShadowMapRes.assigned;
        uniformBuffer.upload(reinterpret_cast<const uint8_t *>(&buf),
                             sizeof(ShaderStorageData));

        auto &gBufPos = resources.get<TextureBuffer>(gBufferPosition);
        auto &gBufNorm = resources.get<TextureBuffer>(gBufferNormal);
        auto &gBufTan = resources.get<TextureBuffer>(gBufferTangent);
        auto &gBufRoughnessMetallicAO = resources.get<TextureBuffer>(gBufferRoughnessMetallicAO);
        auto &gBufAlbedo = resources.get<TextureBuffer>(gBufferAlbedo);
        auto &gBufModelObject = resources.get<TextureBuffer>(gBufferModelObject);
        auto &gBufDepth = resources.get<TextureBuffer>(gBufferDepth);

        target.setAttachments({RenderTargetAttachment::texture(colorTex)}, RenderTargetAttachment::texture(depthTex));

        std::vector<Command> commands;

        commands.emplace_back(pass.begin(target));
        commands.emplace_back(pass.setViewport({}, target.getDescription().size));

        commands.emplace_back(pipeline.bind());
        commands.emplace_back(vertexArrayObject.bind());
        commands.emplace_back(RenderPipeline::bindShaderResources({
                                                                          {uniformBuffer,           {{FRAGMENT, ShaderResource::READ}}},
                                                                          {gBufPos,                 {{FRAGMENT, ShaderResource::READ}}},
                                                                          {gBufNorm,                {{FRAGMENT, ShaderResource::READ}}},
                                                                          {gBufRoughnessMetallicAO, {{FRAGMENT, ShaderResource::READ}}},
                                                                          {gBufAlbedo,              {{FRAGMENT, ShaderResource::READ}}},
                                                                          {gBufModelObject,         {{FRAGMENT, ShaderResource::READ}}},
                                                                          {gBufDepth,               {{FRAGMENT, ShaderResource::READ}}},
                                                                          {pointLightShadowMap,     {{FRAGMENT, ShaderResource::READ}}},
                                                                          {pointLightBuffer,        {{FRAGMENT, ShaderResource::READ}}},
                                                                          {shadowPointLightBuffer,  {{FRAGMENT, ShaderResource::READ}}},
                                                                  }));
        commands.emplace_back(pass.drawArray(DrawCall(0, mesh.vertices.size())));
        commands.emplace_back(pass.end());

        cBuffer.begin();
        cBuffer.add(commands);
        cBuffer.end();

        renderQueues.at(0).get().submit(cBuffer);

        target.clearAttachments();
    }

    std::type_index DeferredLightingPass::getTypeIndex() const {
        return typeid(DeferredLightingPass);
    }
}