/**
 *   xEngine - C++ Game Engine Library
 *   Copyright (C) 2026 Julia Zampiccoli
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   Lesser General Public License for more details.
 *
 *   You should have received a copy of the Lesser General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef XENGINE_RENDERSHADERCOMPILERINDIRECT_HPP
#define XENGINE_RENDERSHADERCOMPILERINDIRECT_HPP

#include "xng/renderer/pipeline/renderpipeline.hpp"
#include "xng/renderer/pipeline/renderpipelinecompiler.hpp"
#include "xng/renderer/objects/rendertexture.hpp"

#include "xng/shaderscript/objectstd140.hpp"
#include "xng/shaderscript/shaderscript.hpp"
#include "xng/shaderscript/macro/shaderstruct.hpp"

namespace xng {
    class XENGINE_EXPORT RenderPipelineCompilerIndirect final : public RenderPipelineCompiler {
    public:
        ShaderStruct(ShaderCamera,
                     Vec4f, viewPosition,
                     Mat4f, view,
                     Mat4f, projection)

        /**
         * Generated by the pre pass, indexed via indirect draw
         */
        ShaderStruct(ShaderDrawMesh,
                     Mat4f, mvp,
                     unsigned int, transformIndex,
                     unsigned int, materialIndex)

        class ShaderTexture {
        public:
            static constexpr auto textureBackingPostfix = "_textureBacking";
            static constexpr auto textureIDPostfix = "_textureID";
            static constexpr auto arrayLayerPostfix = "_arrayLayer";
            static constexpr auto textureSizePostfix = "_textureSize";
            static constexpr auto maxMipPostfix = "_maxMip";
            static constexpr auto minFilterPostfix = "_minFilter";
            static constexpr auto magFilterPostfix = "_magFilter";
            static constexpr auto mipFilterPostfix = "_mipFilter";
            static constexpr auto wrapPostfix = "_wrap";
            static constexpr auto srcRectPostfix = "_srcRect";

            static ShaderScript::Int getTextureBacking(const std::string &name,
                                                       ShaderScript::ShaderObject &object) {
                return object[std::string(name + textureBackingPostfix).c_str()];
            }

            static ShaderScript::Int getTextureID(const std::string &name,
                                                  ShaderScript::ShaderObject &object) {
                return object[std::string(name + textureIDPostfix).c_str()];
            }

            static ShaderScript::Int getArrayLayer(const std::string &name,
                                                   ShaderScript::ShaderObject &object) {
                return object[std::string(name + arrayLayerPostfix).c_str()];
            }

            static ShaderScript::ivec2 getTextureSize(const std::string &name,
                                                      ShaderScript::ShaderObject &object) {
                return object[std::string(name + textureSizePostfix).c_str()];
            }

            static ShaderScript::UInt getMaxMip(const std::string &name, ShaderScript::ShaderObject &object) {
                return object[std::string(name + maxMipPostfix).c_str()];
            }

            static ShaderScript::Int getMinFilter(const std::string &name, ShaderScript::ShaderObject &object) {
                return object[std::string(name + minFilterPostfix).c_str()];
            }

            static ShaderScript::Int getMagFilter(const std::string &name, ShaderScript::ShaderObject &object) {
                return object[std::string(name + magFilterPostfix).c_str()];
            }

            static ShaderScript::Int getMipFilter(const std::string &name, ShaderScript::ShaderObject &object) {
                return object[std::string(name + mipFilterPostfix).c_str()];
            }

            static ShaderScript::Int getWrap(const std::string &name, ShaderScript::ShaderObject &object) {
                return object[std::string(name + wrapPostfix).c_str()];
            }

            static ShaderScript::vec4 getSrcRect(const std::string &name, ShaderScript::ShaderObject &object) {
                return object[std::string(name + srcRectPostfix).c_str()];
            }

            static void setTextureBacking(const std::string &name,
                                          ObjectStd140 &object,
                                          const RenderTexture::TextureBacking value) {
                object.set(name + textureBackingPostfix, static_cast<int>(value));
            }

            static void setTextureID(const std::string &name,
                                     ObjectStd140 &object,
                                     const VirtualTextureStreamer::TextureID &value) {
                object.set(name + textureIDPostfix, static_cast<int>(value));
            }

            static void setArrayLayer(const std::string &name,
                                      ObjectStd140 &object,
                                      const unsigned int value) {
                object.set(name + arrayLayerPostfix, static_cast<int>(value));
            }

            static void setTextureSize(const std::string &name,
                                       ObjectStd140 &object,
                                       const Vec2i &value) {
                object.set(name + textureSizePostfix, value);
            }

            static void setMaxMip(const std::string &name, ObjectStd140 &object, const unsigned int value) {
                object.set(name + maxMipPostfix, value);
            }

            static void setMinFilter(const std::string &name, ObjectStd140 &object, const int value) {
                object.set(name + minFilterPostfix, value);
            }

            static void setMagFilter(const std::string &name, ObjectStd140 &object, const int value) {
                object.set(name + magFilterPostfix, value);
            }

            static void setMipFilter(const std::string &name, ObjectStd140 &object, const int value) {
                object.set(name + mipFilterPostfix, value);
            }

            static void setWrap(const std::string &name, ObjectStd140 &object, const int value) {
                object.set(name + wrapPostfix, value);
            }

            static void setSrcRect(const std::string &name, ObjectStd140 &object, const Vec4f &value) {
                object.set(name + srcRectPostfix, value);
            }

            static void injectLayout(LayoutStd140 &layout, const std::string &name) {
                layout.add(name + textureBackingPostfix, rg::ShaderPrimitiveType::Int());
                layout.add(name + textureIDPostfix, rg::ShaderPrimitiveType::Int());
                layout.add(name + arrayLayerPostfix, rg::ShaderPrimitiveType::Int());
                layout.add(name + textureSizePostfix, rg::ShaderPrimitiveType::ivec2());
                layout.add(name + maxMipPostfix, rg::ShaderPrimitiveType::UInt());
                layout.add(name + minFilterPostfix, rg::ShaderPrimitiveType::Int());
                layout.add(name + magFilterPostfix, rg::ShaderPrimitiveType::Int());
                layout.add(name + mipFilterPostfix, rg::ShaderPrimitiveType::Int());
                layout.add(name + wrapPostfix, rg::ShaderPrimitiveType::Int());
                layout.add(name + srcRectPostfix, rg::ShaderPrimitiveType::vec4());
            }
        };

        static std::string vertexAttributeToName(const VertexAttribute attr) {
            switch (attr) {
                case POSITION:
                    return "_vertex_position";
                case NORMAL:
                    return "_vertex_normal";
                case TANGENT:
                    return "_vertex_tangent";
                case BITANGENT:
                    return "_vertex_bitangent";
                case UV:
                    return "_vertex_uv";
                default:
                    throw std::runtime_error("Invalid vertex attribute");
            }
        }

        static constexpr auto cameraBufferName = "_cameraBuffer";

        static constexpr auto drawMeshBufferName = "_drawMeshBuffer";

        static constexpr auto transformBufferName = "_transforms";

        static constexpr auto materialBufferName = "_materialBuffer";

        static constexpr auto materialPropertyPrefix = "property_";

        static constexpr auto materialTexturePrefix = "texture_";

        static constexpr auto attachmentPrefix = "_attachment_";

        static constexpr auto virtualAtlasTextureName = "_virtualAtlasTexture";

        static constexpr auto virtualTileMapName = "_virtualTileMap";

        static constexpr auto virtualTileMapOffsetsName = "_virtualTileMapOffsets";

        static constexpr auto virtualResidencyMapName = "_virtualResidencyMap";

        static constexpr auto virtualResidencyMapOffsetsName = "_virtualResidencyMapOffsets";

        static constexpr auto virtualReadbackBufferName = "_virtualReadbackBuffer";

        static constexpr auto virtualAtlasSizeName = "_virtualAtlasSize";

        static constexpr auto virtualTileSizeName = "_virtualTileSize";

        static constexpr auto virtualTileBorderName = "_virtualTileBorder";

        static constexpr auto virtualMaxAnisotropyName = "_virtualMaxAnisotropy";

        explicit RenderPipelineCompilerIndirect(rg::PipelineCache &cache,
                                                const RenderPipeline::MaterialLayout &attributes,
                                                const LayoutStd140 &layout)
            : cache(cache), materialLayout(attributes), layout(layout) {
        }

        ~RenderPipelineCompilerIndirect() override = default;

        std::shared_ptr<RenderPipelineShader> compile(const std::vector<rg::Shader> &shaders,
                                                      const rg::RasterPipeline::Configuration &pipelineConfig,
                                                      const std::vector<RenderPipelineShader::Attachment> &
                                                      colorAttachments,
                                                      std::optional<rg::ColorFormat> depthAttachmentFormat,
                                                      std::optional<rg::ColorFormat> stencilAttachmentFormat)
        const override {
            rg::RasterPipeline pipeline;
            pipeline.shaders = shaders;
            pipeline.configuration = pipelineConfig;

            rg::ShaderAttributeLayout vertexLayout;
            for (auto attr = ATTRIBUTE_BEGIN; attr <= ATTRIBUTE_END; attr = static_cast<VertexAttribute>(attr + 1)) {
                vertexLayout.addElement(vertexAttributeToName(attr), getVertexAttributeType(attr));
            }

            for (auto &shader: pipeline.shaders) {
                ShaderScript::ShaderScope scope(shader.stage);

                scope.addTypeDefinition(ShaderCamera::getShaderStructType());
                scope.addStorageBuffer(cameraBufferName,
                                       rg::ShaderStorageBuffer(true,
                                                               false,
                                                               ShaderCamera::getShaderStructType().typeName));

                scope.addStorageBuffer(transformBufferName,
                                       rg::ShaderStorageBuffer(true,
                                                               true,
                                                               rg::ShaderPrimitiveType::mat4()));

                scope.addTypeDefinition(layout.getStructType());
                scope.addStorageBuffer(materialBufferName,
                                       rg::ShaderStorageBuffer(true,
                                                               true,
                                                               layout.getStructType().typeName));

                scope.addTypeDefinition(ShaderDrawMesh::getShaderStructType());
                scope.addStorageBuffer(drawMeshBufferName,
                                       rg::ShaderStorageBuffer(true,
                                                               true,
                                                               std::string(ShaderDrawMesh::_ShaderDrawMesh_type)));

                scope.addTextureArray(virtualAtlasTextureName,
                                      {rg::ShaderTextureArray{rg::ShaderTexture(rg::TEXTURE_2D_ARRAY, rg::RGBA8), 1}});

                scope.addStorageBuffer(virtualTileMapName,
                                       rg::ShaderStorageBuffer(true,
                                                               true,
                                                               rg::ShaderPrimitiveType::UInt()));
                scope.addStorageBuffer(virtualTileMapOffsetsName,
                                       rg::ShaderStorageBuffer(true,
                                                               true,
                                                               rg::ShaderPrimitiveType::UInt()));
                scope.addStorageBuffer(virtualResidencyMapName,
                                       rg::ShaderStorageBuffer(true,
                                                               true,
                                                               rg::ShaderPrimitiveType::UInt()));
                scope.addStorageBuffer(virtualResidencyMapOffsetsName,
                                       rg::ShaderStorageBuffer(true,
                                                               true,
                                                               rg::ShaderPrimitiveType::UInt()));
                scope.addStorageBuffer(virtualReadbackBufferName,
                                       rg::ShaderStorageBuffer(false,
                                                               true,
                                                               rg::ShaderPrimitiveType::UInt()));

                scope.addParameter(virtualAtlasSizeName, rg::ShaderPrimitiveType::UInt());
                scope.addParameter(virtualTileSizeName, rg::ShaderPrimitiveType::UInt());
                scope.addParameter(virtualTileBorderName, rg::ShaderPrimitiveType::UInt());
                scope.addParameter(virtualMaxAnisotropyName, rg::ShaderPrimitiveType::Float());

                compileGetDrawIndex(scope, shader.stage);

                compileGetCameraPosition(scope);
                compileGetModel(scope);
                compileGetView(scope);
                compileGetProjection(scope);
                compileGetModelViewProjection(scope);
                for (auto &attr: materialLayout.properties) {
                    compileGetMaterialProperty(scope, attr.first, attr.second);
                }
                if (shader.stage == rg::Shader::FRAGMENT) {
                    for (auto &tex: materialLayout.textures) {
                        compileSampleMaterialTexture(scope, tex);
                    }
                    for (auto i = 0; i < colorAttachments.size(); i++) {
                        const auto &att = colorAttachments.at(i);
                        compileWriteAttachment(scope, i, att);
                    }
                    shader.inputLayout.addElement("_drawIndex",
                                                  rg::ShaderPrimitiveType::UInt(),
                                                  rg::ShaderAttributeLayout::INTERPOLATE_FLAT);
                } else if (shader.stage == rg::Shader::VERTEX) {
                    for (auto attr = ATTRIBUTE_BEGIN;
                         attr <= ATTRIBUTE_END;
                         attr = static_cast<VertexAttribute>(attr + 1)) {
                        compileGetVertexAttribute(scope, attr);
                    }
                    shader.mainFunction.insert(shader.mainFunction.begin(),
                                               rg::ShaderInstructionFactory::assign(
                                                   rg::ShaderOperand::outputAttribute("_drawIndex"),
                                                   getDrawIndex()));
                    shader.outputLayout.addElement("_drawIndex",
                                                   rg::ShaderPrimitiveType::UInt(),
                                                   rg::ShaderAttributeLayout::INTERPOLATE_FLAT);
                }

                const auto cShader = scope.build();

                // Inject Functions
                for (auto &func: cShader.functions) {
                    for (auto &existingFunc: shader.functions) {
                        if (existingFunc == func) {
                            continue;
                        }
                        if (existingFunc.name == func.name
                            && existingFunc.arguments == func.arguments
                            && existingFunc.returnType == func.returnType) {
                            throw std::runtime_error("Conflicting Function Definitions");
                        }
                    }
                    shader.functions.emplace_back(func);
                }

                // Inject Types
                for (auto &type: cShader.typeDefinitions) {
                    for (auto &existingType: shader.typeDefinitions) {
                        if (existingType == type) {
                            continue;
                        }
                        if (existingType.typeName == type.typeName) {
                            throw std::runtime_error("Conflicting Type Definitions");
                        }
                    }
                    shader.typeDefinitions.emplace_back(type);
                }

                // Inject Buffers
                for (auto &buffer: cShader.storageBuffers) {
                    for (auto &existingBuffer: shader.storageBuffers) {
                        if (existingBuffer == buffer) {
                            continue;
                        }
                        if (existingBuffer.first == buffer.first) {
                            throw std::runtime_error("Conflicting Buffer Definitions");
                        }
                    }
                    shader.storageBuffers[buffer.first] = buffer.second;
                }

                // Inject Textures
                for (auto &tex : cShader.textureArrays) {
                    for (auto &existingTex: shader.textureArrays) {
                        if (existingTex == tex) {
                            continue;
                        }
                        if (existingTex.first == tex.first) {
                            throw std::runtime_error("Conflicting Texture Array Definitions");
                        }
                    }
                    shader.textureArrays[tex.first] = tex.second;
                }

                // Inject Parameters
                for (auto &param: cShader.parameters) {
                    for (auto &existingParam : shader.parameters) {
                        if (existingParam == param) {
                            continue;
                        }
                        if (existingParam.first == param.first) {
                            throw std::runtime_error("Conflicting Parameter Definitions");
                        }
                    }
                    shader.parameters[param.first] = param.second;
                }

                // Inject vertex layout
                if (shader.stage == rg::Shader::VERTEX) {
                    shader.inputLayout = vertexLayout;
                }

                // Inject fragment output layout
                if (shader.stage == rg::Shader::FRAGMENT) {
                    shader.outputLayout = {};
                    for (auto i = 0; i < colorAttachments.size(); i++) {
                        const auto &att = colorAttachments.at(i);
                        if (att.type == RenderPipelineShader::Attachment::ATTACHMENT_NATIVE) {
                            shader.outputLayout.addElement(attachmentPrefix + std::to_string(i),
                                                           att.value);
                        }
                    }
                }
            }

            for (auto &attachment: colorAttachments) {
                if (attachment.type == RenderPipelineShader::Attachment::ATTACHMENT_NATIVE) {
                    pipeline.colorAttachments.emplace_back(attachment.format);
                }
            }
            pipeline.depthAttachment = depthAttachmentFormat;
            pipeline.stencilAttachment = stencilAttachmentFormat;

            std::vector<size_t> offsets;
            offsets.resize(5, 0);

            std::vector<size_t> bindingPoints;
            for (auto attr = ATTRIBUTE_BEGIN; attr <= ATTRIBUTE_END; attr = static_cast<VertexAttribute>(attr + 1)) {
                bindingPoints.emplace_back(attr);
            }

            pipeline.vertexFormat = rg::RasterPipeline::VertexFormat(vertexLayout,
                                                                     bindingPoints,
                                                                     offsets);

            return std::make_shared<RenderPipelineShader>(cache,
                                                          cache.create(pipeline),
                                                          colorAttachments);
        }

        static void compileGetVertexAttribute(ShaderScript::ShaderScope &scope, VertexAttribute attr);

        static void compileGetCameraPosition(ShaderScript::ShaderScope &scope);

        static void compileGetModel(ShaderScript::ShaderScope &scope);

        static void compileGetView(ShaderScript::ShaderScope &scope);

        static void compileGetProjection(ShaderScript::ShaderScope &scope);

        static void compileGetModelViewProjection(ShaderScript::ShaderScope &scope);

        static void compileGetMaterialProperty(ShaderScript::ShaderScope &scope,
                                               RenderPipelineMaterial::PropertyID prop,
                                               rg::ShaderPrimitiveType type);

        static void compileSampleMaterialTexture(ShaderScript::ShaderScope &scope,
                                                 RenderPipelineMaterial::TextureID tex);

        static void compileWriteAttachment(ShaderScript::ShaderScope &scope,
                                           unsigned int index,
                                           const RenderPipelineShader::Attachment &attachment);

        static void compileGetDrawIndex(ShaderScript::ShaderScope &scope,
                                        rg::Shader::Stage stage);

        static rg::ShaderOperand getDrawIndex();

    private:
        rg::PipelineCache &cache;
        const RenderPipeline::MaterialLayout &materialLayout;
        const LayoutStd140 &layout;
    };
}

#endif //XENGINE_RENDERSHADERCOMPILERINDIRECT_HPP
