/**
 *   xEngine - C++ Game Engine Library
 *   Copyright (C) 2026 Julia Zampiccoli
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   Lesser General Public License for more details.
 *
 *   You should have received a copy of the Lesser General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef XENGINE_RENDERSHADERCOMPILERINDIRECT_HPP
#define XENGINE_RENDERSHADERCOMPILERINDIRECT_HPP

#include "xng/renderer/pipeline/rendershadercompiler.hpp"

#include "xng/shaderscript/macro/shaderstruct.hpp"

#include "xng/renderer/objects/rendertexture.hpp"

namespace xng {
    class RenderShaderCompilerIndirect final : public RenderShaderCompiler {
    public:
        ShaderStruct(ShaderCamera,
                     Vec4f, viewPosition,
                     Mat4f, view,
                     Mat4f, projection)

        /**
         * Indexed by the pre pass to build the ShaderDrawMesh list.
         */
        ShaderStruct(ShaderMesh,
                     int, baseVertex,
                     unsigned int, indexOffset, // The first index
                     unsigned int, indexCount,
                     int, modelID, // The ID of the RenderModel object
                     int, meshID, // The ID of the RenderMesh object
                     int, transformIndex,
                     int, materialIndex,
                     bool, receiveShadows)

        /**
         * Generated by the pre pass, indexed via indirect draw
         */
        ShaderStruct(ShaderDrawMesh,
                     Mat4f, mvp,
                     int, modelID,
                     int, meshID,
                     int, transformIndex,
                     int, materialIndex,
                     bool, receiveShadows)

        ShaderStruct(ShaderCanvasPaint,
                     Vec4f, color,
                     float, colorMixFactor,
                     float, alphaMixFactor,
                     Vec4f, uvOffset_uvScale,
                     ShaderTexture, texture)

        ShaderStruct(ShaderConfiguration,
                     float, gamma,
                     bool, ibl)

        rg::ShaderInstruction getVertexAttribute(VertexAttribute attr) override;

        rg::ShaderInstruction getAttribute(RenderShader::InstanceAttribute attr) override;

        rg::ShaderInstruction getAttribute(RenderShader::InstanceAttribute attr, const rg::ShaderInstruction &index) override;

        rg::ShaderInstruction writeAttachment(unsigned index, const rg::ShaderInstruction &color) override;

        std::shared_ptr<RenderShader> compile(const std::vector<rg::Shader> &stages,
                                              const std::vector<RenderShader::Attachment> &attachments,
                                              const std::unordered_set<RenderShader::InstanceAttribute> &attributes,
                                              const std::unordered_set<VertexAttribute> &vertexAttributes) override;
    };
}

#endif //XENGINE_RENDERSHADERCOMPILERINDIRECT_HPP
