/**
 *   xEngine - C++ Game Engine Library
 *   Copyright (C) 2026 Julia Zampiccoli
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   Lesser General Public License for more details.
 *
 *   You should have received a copy of the Lesser General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef XENGINE_RENDERSHADERCOMPILERINDIRECT_HPP
#define XENGINE_RENDERSHADERCOMPILERINDIRECT_HPP

#include "xng/renderer/pipeline/rendershadercompiler.hpp"
#include "xng/renderer/pipeline/renderpipeline.hpp"
#include "xng/renderer/objects/rendertexture.hpp"

#include "xng/shaderscript/objectstd140.hpp"
#include "xng/shaderscript/shaderscript.hpp"
#include "xng/shaderscript/macro/shaderstruct.hpp"

namespace xng {
    class XENGINE_EXPORT RenderShaderCompilerIndirect final : public RenderShaderCompiler {
    public:
        ShaderStruct(ShaderCamera,
                     Vec4f, viewPosition,
                     Mat4f, view,
                     Mat4f, projection)

        ShaderStruct(ShaderDrawCall,
                     int, baseVertex,
                     unsigned int, indexOffset, // The first index
                     unsigned int, indexCount,
                     unsigned int, transformIndex,
                     unsigned int, materialIndex)

        /**
         * Generated by the pre pass, indexed via indirect draw
         */
        ShaderStruct(ShaderDrawMesh,
                     Mat4f, mvp,
                     int, transformIndex,
                     int, materialIndex)

        class ShaderTexture {
        public:
            static constexpr auto textureBackingPostfix = "_textureBacking";
            static constexpr auto textureIDPostfix = "_textureID";
            static constexpr auto arrayLayerPostfix = "_arrayLayer";
            static constexpr auto textureSizePostfix = "_textureSize";
            static constexpr auto maxMipPostfix = "_maxMip";
            static constexpr auto minFilterPostfix = "_minFilter";
            static constexpr auto magFilterPostfix = "_magFilter";
            static constexpr auto mipFilterPostfix = "_mipFilter";
            static constexpr auto wrapPostfix = "_wrap";
            static constexpr auto srcRectPostfix = "_srcRect";

            static ShaderScript::Int getTextureBacking(const std::string &name,
                                                       ShaderScript::ShaderObject &object) {
                return object[std::string(name + textureBackingPostfix).c_str()];
            }

            static ShaderScript::Int getTextureID(const std::string &name,
                                                  ShaderScript::ShaderObject &object) {
                return object[std::string(name + textureIDPostfix).c_str()];
            }

            static ShaderScript::Int getArrayLayer(const std::string &name,
                                                   ShaderScript::ShaderObject &object) {
                return object[std::string(name + arrayLayerPostfix).c_str()];
            }

            static ShaderScript::ivec2 getTextureSize(const std::string &name,
                                                      ShaderScript::ShaderObject &object) {
                return object[std::string(name + textureSizePostfix).c_str()];
            }

            static ShaderScript::Int getMaxMip(const std::string &name, ShaderScript::ShaderObject &object) {
                return object[std::string(name + maxMipPostfix).c_str()];
            }

            static ShaderScript::Int getMinFilter(const std::string &name, ShaderScript::ShaderObject &object) {
                return object[std::string(name + minFilterPostfix).c_str()];
            }

            static ShaderScript::Int getMagFilter(const std::string &name, ShaderScript::ShaderObject &object) {
                return object[std::string(name + magFilterPostfix).c_str()];
            }

            static ShaderScript::Int getMipFilter(const std::string &name, ShaderScript::ShaderObject &object) {
                return object[std::string(name + mipFilterPostfix).c_str()];
            }

            static ShaderScript::Int getWrap(const std::string &name, ShaderScript::ShaderObject &object) {
                return object[std::string(name + wrapPostfix).c_str()];
            }

            static ShaderScript::vec4 getSrcRect(const std::string &name, ShaderScript::ShaderObject &object) {
                return object[std::string(name + srcRectPostfix).c_str()];
            }

            static void setTextureBacking(const std::string &name,
                                          ObjectStd140 &object,
                                          const RenderTexture::TextureBacking value) {
                object.set(name + textureBackingPostfix, static_cast<int>(value));
            }

            static void setTextureID(const std::string &name,
                                     ObjectStd140 &object,
                                     const VirtualTextureStreamer::TextureID &value) {
                object.set(name + textureIDPostfix, static_cast<int>(value));
            }

            static void setArrayLayer(const std::string &name,
                                      ObjectStd140 &object,
                                      const unsigned int value) {
                object.set(name + arrayLayerPostfix, static_cast<int>(value));
            }

            static void setTextureSize(const std::string &name,
                                       ObjectStd140 &object,
                                       const Vec2i &value) {
                object.set(name + textureSizePostfix, value);
            }

            static void setMaxMip(const std::string &name, ObjectStd140 &object, const unsigned int value) {
                object.set(name + maxMipPostfix, value);
            }

            static void setMinFilter(const std::string &name, ObjectStd140 &object, const unsigned int value) {
                object.set(name + minFilterPostfix, value);
            }

            static void setMagFilter(const std::string &name, ObjectStd140 &object, const unsigned int value) {
                object.set(name + magFilterPostfix, value);
            }

            static void setMipFilter(const std::string &name, ObjectStd140 &object, const unsigned int value) {
                object.set(name + mipFilterPostfix, value);
            }

            static void setWrap(const std::string &name, ObjectStd140 &object, const unsigned int value) {
                object.set(name + wrapPostfix, value);
            }

            static void setSrcRect(const std::string &name, ObjectStd140 &object, const Vec4f &value) {
                object.set(name + srcRectPostfix, value);
            }

            static void injectLayout(LayoutStd140 &layout, const std::string &name) {
                layout.add(name + textureBackingPostfix, rg::ShaderPrimitiveType::Int());
                layout.add(name + textureIDPostfix, rg::ShaderPrimitiveType::Int());
                layout.add(name + arrayLayerPostfix, rg::ShaderPrimitiveType::Int());
                layout.add(name + textureSizePostfix, rg::ShaderPrimitiveType::ivec2());
                layout.add(name + maxMipPostfix, rg::ShaderPrimitiveType::Int());
                layout.add(name + minFilterPostfix, rg::ShaderPrimitiveType::Int());
                layout.add(name + magFilterPostfix, rg::ShaderPrimitiveType::Int());
                layout.add(name + mipFilterPostfix, rg::ShaderPrimitiveType::Int());
                layout.add(name + wrapPostfix, rg::ShaderPrimitiveType::Int());
                layout.add(name + srcRectPostfix, rg::ShaderPrimitiveType::vec4());
            }
        };

        static std::string vertexAttributeToName(const VertexAttribute attr) {
            switch (attr) {
                case POSITION:
                    return "_vertex_position";
                case NORMAL:
                    return "_vertex_normal";
                case TANGENT:
                    return "_vertex_tangent";
                case BITANGENT:
                    return "_vertex_bitangent";
                case UV:
                    return "_vertex_uv";
                default:
                    throw std::runtime_error("Invalid vertex attribute");
            }
        }

        static constexpr auto cameraBufferName = "_cameraBuffer";

        static constexpr auto drawMeshBufferName = "_drawMeshBuffer";

        static constexpr auto transformBufferName = "_transforms";

        static constexpr auto materialBufferName = "_materialBuffer";

        static constexpr auto materialPropertyPrefix = "property_";

        static constexpr auto materialTexturePrefix = "texture_";

        static constexpr auto attachmentPrefix = "_attachment_";

        static constexpr auto virtualAtlasTextureName = "_virtualAtlasTexture";

        static constexpr auto virtualTileMapName = "_virtualTileMap";

        static constexpr auto virtualTileMapOffsetsName = "_virtualTileMapOffsets";

        static constexpr auto virtualResidencyMapName = "_virtualResidencyMap";

        static constexpr auto virtualResidencyMapOffsetsName = "_virtualResidencyMapOffsets";

        static constexpr auto virtualReadbackBufferName = "_virtualReadbackBuffer";

        static constexpr auto virtualAtlasSizeName = "_virtualAtlasSize";

        static constexpr auto virtualTileSizeName = "_virtualTileSize";

        static constexpr auto virtualTileBorderName = "_virtualTileBorder";

        static constexpr auto virtualMaxAnisotropyName = "_virtualMaxAnisotropy";

        explicit RenderShaderCompilerIndirect(rg::PipelineCache &cache,
                                              const RenderPipeline::MaterialLayout &attributes,
                                              const LayoutStd140 &layout)
            : cache(cache), materialLayout(attributes), layout(layout) {
        }

        ~RenderShaderCompilerIndirect() override = default;

        rg::ShaderOperand getVertexAttribute(const VertexAttribute attr) override {
            return rg::ShaderOperand::inputAttribute(vertexAttributeToName(attr));
        }

        rg::ShaderOperand getCameraPosition() override {
            return rg::ShaderOperand::instruction(rg::ShaderInstructionFactory::call("getCameraPosition", {}));
        }

        rg::ShaderOperand getModel() override {
            return rg::ShaderOperand::instruction(rg::ShaderInstructionFactory::call("getModel", {}));
        }

        rg::ShaderOperand getView() override {
            return rg::ShaderOperand::instruction(rg::ShaderInstructionFactory::call("getView", {}));
        }

        rg::ShaderOperand getProjection() override {
            return rg::ShaderOperand::instruction(rg::ShaderInstructionFactory::call("getProjection", {}));
        }

        rg::ShaderOperand getModelViewProjection() override {
            return rg::ShaderOperand::instruction(rg::ShaderInstructionFactory::call("getModelViewProjection", {}));
        }

        rg::ShaderOperand getMaterialProperty(const RenderPipelineMaterial::PropertyID attr) override {
            return rg::ShaderOperand::instruction(rg::ShaderInstructionFactory::call("getMaterialProperty"
                    + std::to_string(attr), {}));
        }

        rg::ShaderOperand sampleMaterialTexture(const RenderPipelineMaterial::TextureID tex,
                                                const rg::ShaderOperand &uv) override {
            return rg::ShaderOperand::instruction(rg::ShaderInstructionFactory::call("sampleMaterialTexture"
                    + std::to_string(tex), {uv}));
        }

        rg::ShaderInstruction writeAttachment(const unsigned index, const rg::ShaderOperand &color) override {
            return rg::ShaderInstructionFactory::call("writeAttachment" + std::to_string(index), {color});
        }

        std::shared_ptr<RenderShader> compile(const std::vector<rg::Shader> &shaders,
                                              const rg::RasterPipeline::Configuration &pipelineConfig,
                                              const std::vector<RenderShader::Attachment> &colorAttachments,
                                              const std::optional<rg::ColorFormat> &depthAttachment,
                                              const std::optional<rg::ColorFormat> &stencilAttachment,
                                              const std::unordered_set<VertexAttribute> &vertexAttributes,
                                              const std::unordered_set<RenderPipelineMaterial::PropertyID> &
                                              accessedProperties,
                                              const std::unordered_set<RenderPipelineMaterial::TextureID> &
                                              accessedTextures) override {
            rg::RasterPipeline pipeline;
            pipeline.shaders = shaders;
            pipeline.configuration = pipelineConfig;
            for (auto &shader: pipeline.shaders) {
                ShaderScript::ShaderScope scope(shader.stage);

                scope.addTypeDefinition(ShaderCamera::getShaderStructType());
                scope.addBuffer(cameraBufferName,
                                rg::ShaderBuffer(true,
                                                 false,
                                                 ShaderCamera::getShaderStructType().typeName));

                scope.addBuffer(transformBufferName,
                                rg::ShaderBuffer(true,
                                                 true,
                                                 rg::ShaderPrimitiveType::mat4()));

                scope.addTypeDefinition(layout.getStructType());
                scope.addBuffer(materialBufferName,
                                rg::ShaderBuffer(true,
                                                 true,
                                                 layout.getStructType().typeName));

                scope.addTypeDefinition(ShaderDrawCall::getShaderStructType());
                scope.addBuffer(drawMeshBufferName,
                                rg::ShaderBuffer(true,
                                                 true,
                                                 std::string(ShaderDrawMesh::_ShaderDrawMesh_type)));

                compileGetCameraPosition(scope);
                compileGetModel(scope);
                compileGetView(scope);
                compileGetProjection(scope);
                compileGetModelViewProjection(scope);
                for (auto &attr: accessedProperties) {
                    compileGetMaterialProperty(scope, attr, materialLayout.properties.at(attr));
                }
                for (auto &tex: accessedTextures) {
                    compileSampleMaterialTexture(scope, tex);
                }
                for (auto i = 0; i < colorAttachments.size(); i++) {
                    const auto &att = colorAttachments.at(i);
                    compileWriteAttachment(scope, i, att);
                }

                const auto cShader = scope.build();

                // Inject Functions
                for (auto &func: cShader.functions) {
                    for (auto &existingFunc: shader.functions) {
                        if (existingFunc == func) {
                            continue;
                        }
                        if (existingFunc.name == func.name
                            && existingFunc.arguments == func.arguments
                            && existingFunc.returnType == func.returnType) {
                            throw std::runtime_error("Conflicting Function Definitions");
                        }
                    }
                    shader.functions.emplace_back(func);
                }

                // Inject Types
                for (auto &type: cShader.typeDefinitions) {
                    for (auto &existingType: shader.typeDefinitions) {
                        if (existingType == type) {
                            continue;
                        }
                        if (existingType.typeName == type.typeName) {
                            throw std::runtime_error("Conflicting Type Definitions");
                        }
                    }
                    shader.typeDefinitions.emplace_back(type);
                }

                // Inject Buffers
                for (auto &buffer: cShader.buffers) {
                    for (auto &existingBuffer: shader.buffers) {
                        if (existingBuffer == buffer) {
                            continue;
                        }
                        if (existingBuffer.first == buffer.first) {
                            throw std::runtime_error("Conflicting Buffer Definitions");
                        }
                    }
                }

                // Inject vertex layout
                if (shader.stage == rg::Shader::VERTEX) {
                    shader.inputLayout = {};
                    shader.inputLayout.addElement(vertexAttributeToName(POSITION),
                                                  rg::ShaderPrimitiveType::vec3());
                    shader.inputLayout.addElement(vertexAttributeToName(NORMAL),
                                                  rg::ShaderPrimitiveType::vec3());
                    shader.inputLayout.addElement(vertexAttributeToName(TANGENT), rg::ShaderPrimitiveType::vec3());
                    shader.inputLayout.addElement(vertexAttributeToName(BITANGENT), rg::ShaderPrimitiveType::vec3());
                    shader.inputLayout.addElement(vertexAttributeToName(UV), rg::ShaderPrimitiveType::vec2());
                }

                // Inject fragment output layout
                if (shader.stage == rg::Shader::FRAGMENT) {
                    shader.outputLayout = {};
                    for (auto i = 0; i < colorAttachments.size(); i++) {
                        const auto &att = colorAttachments.at(i);
                        if (att.type == RenderShader::Attachment::ATTACHMENT_NATIVE) {
                            shader.outputLayout.addElement(attachmentPrefix + std::to_string(i),
                                                           att.value);
                        }
                    }
                }
            }

            for (auto &attachment : colorAttachments) {
                if (attachment.type == RenderShader::Attachment::ATTACHMENT_NATIVE) {
                    pipeline.colorAttachments.emplace_back(attachment.format);
                }
            }
            pipeline.depthAttachment = depthAttachment;
            pipeline.stencilAttachment = stencilAttachment;

            // TODO: Pipeline vertex format definition
            pipeline.vertexFormat.bindingPoints;

            return std::make_shared<RenderShader>(cache,
                                                  cache.create(pipeline),
                                                  colorAttachments,
                                                  vertexAttributes,
                                                  accessedProperties,
                                                  accessedTextures);
        }

        static void compileGetCameraPosition(ShaderScript::ShaderScope &scope);

        static void compileGetModel(ShaderScript::ShaderScope &scope);

        static void compileGetView(ShaderScript::ShaderScope &scope);

        static void compileGetProjection(ShaderScript::ShaderScope &scope);

        static void compileGetModelViewProjection(ShaderScript::ShaderScope &scope);

        static void compileGetMaterialProperty(ShaderScript::ShaderScope &scope,
                                               RenderPipelineMaterial::PropertyID prop,
                                               rg::ShaderPrimitiveType type);

        static void compileSampleMaterialTexture(ShaderScript::ShaderScope &scope,
                                                 RenderPipelineMaterial::TextureID tex);

        static void compileWriteAttachment(ShaderScript::ShaderScope &scope,
                                           unsigned int index,
                                           const RenderShader::Attachment &attachment);

    private:
        rg::PipelineCache &cache;
        const RenderPipeline::MaterialLayout &materialLayout;
        const LayoutStd140 &layout;
    };
}

#endif //XENGINE_RENDERSHADERCOMPILERINDIRECT_HPP
