/**
 *   xEngine - C++ Game Engine Library
 *   Copyright (C) 2026 Julia Zampiccoli
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   Lesser General Public License for more details.
 *
 *   You should have received a copy of the Lesser General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef XENGINE_RENDERSHADERCOMPILERINDIRECT_HPP
#define XENGINE_RENDERSHADERCOMPILERINDIRECT_HPP

#include "xng/renderer/pipeline/rendershadercompiler.hpp"

#include "xng/shaderscript/macro/shaderstruct.hpp"

#include "xng/renderer/objects/rendertexture.hpp"

#include "xng/shaderscript/objectstd140.hpp"

namespace xng {
    class RenderShaderCompilerIndirect final : public RenderShaderCompiler {
    public:
        ShaderStruct(ShaderDrawCall,
                     int, baseVertex,
                     unsigned int, indexOffset, // The first index
                     unsigned int, indexCount,
                     unsigned int, transformIndex,
                     unsigned int, attributesIndex)

        ShaderStruct(ShaderCamera,
                     Vec4f, viewPosition,
                     Mat4f, view,
                     Mat4f, projection)

        /**
         * Generated by the pre pass, indexed via indirect draw
         */
        ShaderStruct(ShaderDrawMesh,
                     Mat4f, mvp,
                     int, transformIndex,
                     int, attributesIndex)

        static void addTexture(const std::string &name, LayoutStd140 &layout) {
            layout.add(name + "_textureBacking", rg::ShaderPrimitiveType::Int());
            layout.add(name + "_textureID", rg::ShaderPrimitiveType::Int());
            layout.add(name + "_arrayLayer", rg::ShaderPrimitiveType::Int());
            layout.add(name + "_textureSize", rg::ShaderPrimitiveType::ivec2());
            layout.add(name + "_maxMip", rg::ShaderPrimitiveType::Int());
            layout.add(name + "_minFilter", rg::ShaderPrimitiveType::Int());
            layout.add(name + "_magFilter", rg::ShaderPrimitiveType::Int());
            layout.add(name + "_mipFilter", rg::ShaderPrimitiveType::Int());
            layout.add(name + "_wrap", rg::ShaderPrimitiveType::Int());
            layout.add(name + "_mixColor", rg::ShaderPrimitiveType::vec4());
            layout.add(name + "_mix", rg::ShaderPrimitiveType::Float());
            layout.add(name + "_srcRect", rg::ShaderPrimitiveType::vec4());
        }

        static void setTexture(const std::string &name,
                               ObjectStd140 &object,
                               const RenderObjectHandle<RenderTexture> &texture) {
            object.set(name + "_textureID", texture->getHandle());
        }

        static std::string vertexAttributeToName(const VertexAttribute attr) {
            switch (attr) {
                case POSITION:
                    return "_vertex_position";
                case NORMAL:
                    return "_vertex_normal";
                case TANGENT:
                    return "_vertex_tangent";
                case BITANGENT:
                    return "_vertex_bitangent";
                case UV:
                    return "_vertex_uv";
                default:
                    throw std::runtime_error("Invalid vertex attribute");
            }
        }

        static constexpr auto cameraBufferName = "_cameraBuffer";

        static constexpr auto drawMeshBufferName = "_drawMeshBuffer";

        static constexpr auto transformBufferName = "_transforms";

        static constexpr auto instanceAttributesBufferName = "_instanceAttributes";

        static constexpr auto globalAttributesBufferName = "_globalAttributes";

        static constexpr auto arrayAttributesBufferPrefix = "_arrayAttributes_";

        ~RenderShaderCompilerIndirect() override = default;

        rg::ShaderOperand getVertexAttribute(const VertexAttribute attr) override {
            return rg::ShaderOperand::inputAttribute(vertexAttributeToName(attr));
        }

        rg::ShaderOperand getCameraPosition() override {
            return rg::ShaderOperand::instruction(rg::ShaderInstructionFactory::call("getCameraPosition", {}));
        }

        rg::ShaderOperand getModel() override {
            return rg::ShaderOperand::instruction(rg::ShaderInstructionFactory::call("getModel", {}));
        }

        rg::ShaderOperand getView() override {
            return rg::ShaderOperand::instruction(rg::ShaderInstructionFactory::call("getView", {}));
        }

        rg::ShaderOperand getProjection() override {
            return rg::ShaderOperand::instruction(rg::ShaderInstructionFactory::call("getProjection", {}));
        }

        rg::ShaderOperand getModelViewProjection() override {
            return rg::ShaderOperand::instruction(rg::ShaderInstructionFactory::call("getModelViewProjection", {}));
        }

        rg::ShaderOperand getMaterialAttribute(RenderPipelineMaterial::AttributeID attr) override {
            return rg::ShaderOperand::instruction(rg::ShaderInstructionFactory::call("getMaterialAttribute"
                + std::to_string(attr), {}));
        }

        rg::ShaderInstruction writeAttachment(const unsigned index, const rg::ShaderOperand &color) override {
            return rg::ShaderInstructionFactory::call("writeAttachment" + std::to_string(index), {color});
        }

        std::shared_ptr<RenderShader> compile(const rg::RasterPipeline &pipeline,
                                              const std::vector<RenderShader::Attachment> &attachments,
                                              const std::unordered_set<VertexAttribute> &vertexAttributes,
                                              const std::unordered_set<RenderPipelineMaterial::AttributeID> &
                                              materialAttributes) override {
            rg::RasterPipeline pip = pipeline;
            return nullptr;
        }
    };
}

#endif //XENGINE_RENDERSHADERCOMPILERINDIRECT_HPP
