/**
 *  xEngine - C++ Game Engine Library
 *  Copyright (C) 2025 Julian Zampiccoli
 *
 *  This program is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 3 of the License, or (at your option) any later version.

 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.

 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program; if not, write to the Free Software Foundation,
 *  Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

#ifndef XENGINE_RENDERGRAPH_SHADERSTRUCT_HPP
#define XENGINE_RENDERGRAPH_SHADERSTRUCT_HPP

#include <array>
#include <type_traits>

#include "xng/rendergraph/shader/shaderstructdef.hpp"

#include "xng/shaderscript/shaderobject.hpp"
#include "xng/shaderscript/std140.hpp"

using namespace xng::rendergraph;

/**
 * This header defines macros to make shader struct definition simpler and cleaner and allow
 * a single source of truth definition for both the shader script side structure definition and the
 * corresponding C++ side structure definition with matching memory layout.
 */
namespace xng::ShaderScript
{
    // Maps a C++ scalar type to the corresponding ShaderPrimitiveType::Component enum value.
    template <typename T>
    struct ShaderComponentOf;

    template <>
    struct ShaderComponentOf<bool>
    {
        static constexpr ShaderPrimitiveType::Component value = ShaderPrimitiveType::BOOLEAN;
    };

    template <>
    struct ShaderComponentOf<int>
    {
        static constexpr ShaderPrimitiveType::Component value = ShaderPrimitiveType::SIGNED_INT;
    };

    template <>
    struct ShaderComponentOf<unsigned int>
    {
        static constexpr ShaderPrimitiveType::Component value = ShaderPrimitiveType::UNSIGNED_INT;
    };

    template <>
    struct ShaderComponentOf<float>
    {
        static constexpr ShaderPrimitiveType::Component value = ShaderPrimitiveType::FLOAT;
    };

    template <>
    struct ShaderComponentOf<double>
    {
        static constexpr ShaderPrimitiveType::Component value = ShaderPrimitiveType::DOUBLE;
    };

    // Extracts template parameters from a ShaderDataObject instantiation.
    template <typename T>
    struct ShaderDataObjectTraits;

    template <ShaderPrimitiveType::Type TYPE, ShaderPrimitiveType::Component COMP, size_t C>
    struct ShaderDataObjectTraits<ShaderDataObject<TYPE, COMP, C>>
    {
        static constexpr ShaderPrimitiveType::Type value_type = TYPE;
        static constexpr ShaderPrimitiveType::Component component = COMP;
        static constexpr size_t count = C;
    };

    // Maps a C++ math type to its DSL ShaderDataObject type.
    // Primary: undefined (compile error for unsupported types).
    // DSL struct types (generated by DefineStruct) expose a nested CPU type
    // and are detected by the partial specialization below — they ARE their own DSL type.
    template <typename T, typename = void>
    struct ShaderTypeOf;

    template <>
    struct ShaderTypeOf<bool>
    {
        using type = ShaderDataObject<ShaderPrimitiveType::SCALAR, ShaderPrimitiveType::BOOLEAN, 1>;
    };

    template <>
    struct ShaderTypeOf<int>
    {
        using type = ShaderDataObject<ShaderPrimitiveType::SCALAR, ShaderPrimitiveType::SIGNED_INT, 1>;
    };

    template <>
    struct ShaderTypeOf<unsigned int>
    {
        using type = ShaderDataObject<ShaderPrimitiveType::SCALAR, ShaderPrimitiveType::UNSIGNED_INT, 1>;
    };

    template <>
    struct ShaderTypeOf<float>
    {
        using type = ShaderDataObject<ShaderPrimitiveType::SCALAR, ShaderPrimitiveType::FLOAT, 1>;
    };

    template <>
    struct ShaderTypeOf<double>
    {
        using type = ShaderDataObject<ShaderPrimitiveType::SCALAR, ShaderPrimitiveType::DOUBLE, 1>;
    };

    template <typename T>
    struct ShaderTypeOf<Vector2<T>>
    {
        using type = ShaderDataObject<ShaderPrimitiveType::VECTOR2, ShaderComponentOf<T>::value, 1>;
    };

    template <typename T>
    struct ShaderTypeOf<Vector3<T>>
    {
        using type = ShaderDataObject<ShaderPrimitiveType::VECTOR3, ShaderComponentOf<T>::value, 1>;
    };

    template <typename T>
    struct ShaderTypeOf<Vector4<T>>
    {
        using type = ShaderDataObject<ShaderPrimitiveType::VECTOR4, ShaderComponentOf<T>::value, 1>;
    };

    template <typename T>
    struct ShaderTypeOf<Matrix<T, 2, 2>>
    {
        using type = ShaderDataObject<ShaderPrimitiveType::MAT2, ShaderComponentOf<T>::value, 1>;
    };

    template <typename T>
    struct ShaderTypeOf<Matrix<T, 3, 3>>
    {
        using type = ShaderDataObject<ShaderPrimitiveType::MAT3, ShaderComponentOf<T>::value, 1>;
    };

    template <typename T>
    struct ShaderTypeOf<Matrix<T, 4, 4>>
    {
        using type = ShaderDataObject<ShaderPrimitiveType::MAT4, ShaderComponentOf<T>::value, 1>;
    };

    template <typename T, size_t N>
    struct ShaderTypeOf<std::array<T, N>>
    {
    private:
        using traits = ShaderDataObjectTraits<typename ShaderTypeOf<T>::type>;

    public:
        using type = ShaderDataObject<traits::value_type, traits::component, (int)N>;
    };

    // DSL struct types: detected by presence of nested T::CPU.
    // The struct itself IS the DSL type — no wrapping needed.
    template <typename T>
    struct ShaderTypeOf<T, std::void_t<typename T::CPU>>
    {
        using type = T;
    };

    template <typename T, typename = void>
    struct ShaderCpuTypeOf
    {
        using type = Std140<T>;
    };

    template <typename T>
    struct ShaderCpuTypeOf<T, std::void_t<typename T::CPU>>
    {
        using type = typename T::CPU;
    };

    template <typename T>
    using ShaderCpuType = typename ShaderCpuTypeOf<T>::type;
}

#define GetGenerator(_type0, _name0, \
    _type1, _name1, \
    _type2, _name2, \
    _type3, _name3, \
    _type4, _name4, \
    _type5, _name5, \
    _type6, _name6, \
    _type7, _name7, \
    _type8, _name8, \
    _type9, _name9, \
    _type10, _name10, \
    _type11, _name11, \
    _type12, _name12, \
    _type13, _name13, \
    _type14, _name14, \
    _type15, _name15, \
    _type16, _name16, \
    _type17, _name17, \
    _type18, _name18, \
    _type19, _name19, \
    _type20, _name20, \
    _type21, _name21, \
    _type22, _name22, \
    _type23, _name23, \
    _type24, _name24, \
    _type25, _name25, \
    _type26, _name26, \
    _type27, _name27, \
    _type28, _name28, \
    _type29, _name29, \
    _type30, _name30, \
    _type31, _name31, \
    _type32, _name32, \
    _type33, _name33, \
    _type34, _name34, \
    _type35, _name35, \
    _type36, _name36, \
    _type37, _name37, \
    _type38, _name38, \
    _type39, _name39, \
    _type40, _name40, \
    _type41, _name41, \
    _type42, _name42, \
    _type43, _name43, \
    _type44, _name44, \
    _type45, _name45, \
    _type46, _name46, \
    _type47, _name47, \
    _type48, _name48, \
    _type49, _name49, \
    NAME, ...) NAME

// In MSVC preprocessor __VA_ARGS__ is treated as a single token in macro argument lists.
// According to this: https://stackoverflow.com/a/32400131
// when wrapping __VA_ARGS__ usage in another macro invocation, it forces the preprocessor to not treat __VA_ARGS__ as a single token.
#define ExpandVAArgs(v) v

#define GenerateElementDeclaration1(_type, name) xng::ShaderScript::ShaderTypeOf<_type>::type name;
#define GenerateElementDeclaration2(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration1(__VA_ARGS__))
#define GenerateElementDeclaration3(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration2(__VA_ARGS__))
#define GenerateElementDeclaration4(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration3(__VA_ARGS__))
#define GenerateElementDeclaration5(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration4(__VA_ARGS__))
#define GenerateElementDeclaration6(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration5(__VA_ARGS__))
#define GenerateElementDeclaration7(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration6(__VA_ARGS__))
#define GenerateElementDeclaration8(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration7(__VA_ARGS__))
#define GenerateElementDeclaration9(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration8(__VA_ARGS__))
#define GenerateElementDeclaration10(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration9(__VA_ARGS__))
#define GenerateElementDeclaration11(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration10(__VA_ARGS__))
#define GenerateElementDeclaration12(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration11(__VA_ARGS__))
#define GenerateElementDeclaration13(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration12(__VA_ARGS__))
#define GenerateElementDeclaration14(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration13(__VA_ARGS__))
#define GenerateElementDeclaration15(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration14(__VA_ARGS__))
#define GenerateElementDeclaration16(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration15(__VA_ARGS__))
#define GenerateElementDeclaration17(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration16(__VA_ARGS__))
#define GenerateElementDeclaration18(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration17(__VA_ARGS__))
#define GenerateElementDeclaration19(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration18(__VA_ARGS__))
#define GenerateElementDeclaration20(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration19(__VA_ARGS__))
#define GenerateElementDeclaration21(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration20(__VA_ARGS__))
#define GenerateElementDeclaration22(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration21(__VA_ARGS__))
#define GenerateElementDeclaration23(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration22(__VA_ARGS__))
#define GenerateElementDeclaration24(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration23(__VA_ARGS__))
#define GenerateElementDeclaration25(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration24(__VA_ARGS__))
#define GenerateElementDeclaration26(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration25(__VA_ARGS__))
#define GenerateElementDeclaration27(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration26(__VA_ARGS__))
#define GenerateElementDeclaration28(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration27(__VA_ARGS__))
#define GenerateElementDeclaration29(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration28(__VA_ARGS__))
#define GenerateElementDeclaration30(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration29(__VA_ARGS__))
#define GenerateElementDeclaration31(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration30(__VA_ARGS__))
#define GenerateElementDeclaration32(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration31(__VA_ARGS__))
#define GenerateElementDeclaration33(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration32(__VA_ARGS__))
#define GenerateElementDeclaration34(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration33(__VA_ARGS__))
#define GenerateElementDeclaration35(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration34(__VA_ARGS__))
#define GenerateElementDeclaration36(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration35(__VA_ARGS__))
#define GenerateElementDeclaration37(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration36(__VA_ARGS__))
#define GenerateElementDeclaration38(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration37(__VA_ARGS__))
#define GenerateElementDeclaration39(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration38(__VA_ARGS__))
#define GenerateElementDeclaration40(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration39(__VA_ARGS__))
#define GenerateElementDeclaration41(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration40(__VA_ARGS__))
#define GenerateElementDeclaration42(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration41(__VA_ARGS__))
#define GenerateElementDeclaration43(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration42(__VA_ARGS__))
#define GenerateElementDeclaration44(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration43(__VA_ARGS__))
#define GenerateElementDeclaration45(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration44(__VA_ARGS__))
#define GenerateElementDeclaration46(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration45(__VA_ARGS__))
#define GenerateElementDeclaration47(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration46(__VA_ARGS__))
#define GenerateElementDeclaration48(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration47(__VA_ARGS__))
#define GenerateElementDeclaration49(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration48(__VA_ARGS__))
#define GenerateElementDeclaration50(type, name, ...) GenerateElementDeclaration1(type, name) ExpandVAArgs(GenerateElementDeclaration49(__VA_ARGS__))

#define GenerateElementDeclaration(...) ExpandVAArgs(GetGenerator(__VA_ARGS__,\
    GenerateElementDeclaration50, GenerateElementDeclaration50,\
    GenerateElementDeclaration49, GenerateElementDeclaration49,\
    GenerateElementDeclaration48, GenerateElementDeclaration48,\
    GenerateElementDeclaration47, GenerateElementDeclaration47,\
    GenerateElementDeclaration46, GenerateElementDeclaration46,\
    GenerateElementDeclaration45, GenerateElementDeclaration45,\
    GenerateElementDeclaration44, GenerateElementDeclaration44,\
    GenerateElementDeclaration43, GenerateElementDeclaration43,\
    GenerateElementDeclaration42, GenerateElementDeclaration42,\
    GenerateElementDeclaration41, GenerateElementDeclaration41,\
    GenerateElementDeclaration40, GenerateElementDeclaration40,\
    GenerateElementDeclaration39, GenerateElementDeclaration39,\
    GenerateElementDeclaration38, GenerateElementDeclaration38,\
    GenerateElementDeclaration37, GenerateElementDeclaration37,\
    GenerateElementDeclaration36, GenerateElementDeclaration36,\
    GenerateElementDeclaration35, GenerateElementDeclaration35,\
    GenerateElementDeclaration34, GenerateElementDeclaration34,\
    GenerateElementDeclaration33, GenerateElementDeclaration33,\
    GenerateElementDeclaration32, GenerateElementDeclaration32,\
    GenerateElementDeclaration31, GenerateElementDeclaration31,\
    GenerateElementDeclaration30, GenerateElementDeclaration30,\
    GenerateElementDeclaration29, GenerateElementDeclaration29,\
    GenerateElementDeclaration28, GenerateElementDeclaration28,\
    GenerateElementDeclaration27, GenerateElementDeclaration27,\
    GenerateElementDeclaration26, GenerateElementDeclaration26,\
    GenerateElementDeclaration25, GenerateElementDeclaration25,\
    GenerateElementDeclaration24, GenerateElementDeclaration24,\
    GenerateElementDeclaration23, GenerateElementDeclaration23,\
    GenerateElementDeclaration22, GenerateElementDeclaration22,\
    GenerateElementDeclaration21, GenerateElementDeclaration21,\
    GenerateElementDeclaration20, GenerateElementDeclaration20,\
    GenerateElementDeclaration19, GenerateElementDeclaration19,\
    GenerateElementDeclaration18, GenerateElementDeclaration18,\
    GenerateElementDeclaration17, GenerateElementDeclaration17,\
    GenerateElementDeclaration16, GenerateElementDeclaration16,\
    GenerateElementDeclaration15, GenerateElementDeclaration15,\
    GenerateElementDeclaration14, GenerateElementDeclaration14,\
    GenerateElementDeclaration13, GenerateElementDeclaration13,\
    GenerateElementDeclaration12, GenerateElementDeclaration12,\
    GenerateElementDeclaration11, GenerateElementDeclaration11,\
    GenerateElementDeclaration10, GenerateElementDeclaration10,\
    GenerateElementDeclaration9, GenerateElementDeclaration9,\
    GenerateElementDeclaration8, GenerateElementDeclaration8,\
    GenerateElementDeclaration7, GenerateElementDeclaration7,\
    GenerateElementDeclaration6, GenerateElementDeclaration6,\
    GenerateElementDeclaration5, GenerateElementDeclaration5,\
    GenerateElementDeclaration4, GenerateElementDeclaration4,\
    GenerateElementDeclaration3, GenerateElementDeclaration3,\
    GenerateElementDeclaration2, GenerateElementDeclaration2,\
    GenerateElementDeclaration1, GenerateElementDeclaration1)(__VA_ARGS__))

#define GenerateConstructor1(_type, name) name(xng::ShaderScript::ShaderTypeOf<_type>::type(ShaderInstructionFactory::objectMember(_object.operand, #name)))
#define GenerateConstructor2(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor1(__VA_ARGS__))
#define GenerateConstructor3(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor2(__VA_ARGS__))
#define GenerateConstructor4(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor3(__VA_ARGS__))
#define GenerateConstructor5(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor4(__VA_ARGS__))
#define GenerateConstructor6(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor5(__VA_ARGS__))
#define GenerateConstructor7(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor6(__VA_ARGS__))
#define GenerateConstructor8(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor7(__VA_ARGS__))
#define GenerateConstructor9(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor8(__VA_ARGS__))
#define GenerateConstructor10(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor9(__VA_ARGS__))
#define GenerateConstructor11(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor10(__VA_ARGS__))
#define GenerateConstructor12(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor11(__VA_ARGS__))
#define GenerateConstructor13(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor12(__VA_ARGS__))
#define GenerateConstructor14(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor13(__VA_ARGS__))
#define GenerateConstructor15(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor14(__VA_ARGS__))
#define GenerateConstructor16(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor15(__VA_ARGS__))
#define GenerateConstructor17(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor16(__VA_ARGS__))
#define GenerateConstructor18(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor17(__VA_ARGS__))
#define GenerateConstructor19(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor18(__VA_ARGS__))
#define GenerateConstructor20(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor19(__VA_ARGS__))
#define GenerateConstructor21(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor20(__VA_ARGS__))
#define GenerateConstructor22(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor21(__VA_ARGS__))
#define GenerateConstructor23(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor22(__VA_ARGS__))
#define GenerateConstructor24(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor23(__VA_ARGS__))
#define GenerateConstructor25(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor24(__VA_ARGS__))
#define GenerateConstructor26(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor25(__VA_ARGS__))
#define GenerateConstructor27(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor26(__VA_ARGS__))
#define GenerateConstructor28(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor27(__VA_ARGS__))
#define GenerateConstructor29(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor28(__VA_ARGS__))
#define GenerateConstructor30(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor29(__VA_ARGS__))
#define GenerateConstructor31(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor30(__VA_ARGS__))
#define GenerateConstructor32(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor31(__VA_ARGS__))
#define GenerateConstructor33(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor32(__VA_ARGS__))
#define GenerateConstructor34(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor33(__VA_ARGS__))
#define GenerateConstructor35(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor34(__VA_ARGS__))
#define GenerateConstructor36(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor35(__VA_ARGS__))
#define GenerateConstructor37(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor36(__VA_ARGS__))
#define GenerateConstructor38(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor37(__VA_ARGS__))
#define GenerateConstructor39(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor38(__VA_ARGS__))
#define GenerateConstructor40(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor39(__VA_ARGS__))
#define GenerateConstructor41(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor40(__VA_ARGS__))
#define GenerateConstructor42(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor41(__VA_ARGS__))
#define GenerateConstructor43(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor42(__VA_ARGS__))
#define GenerateConstructor44(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor43(__VA_ARGS__))
#define GenerateConstructor45(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor44(__VA_ARGS__))
#define GenerateConstructor46(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor45(__VA_ARGS__))
#define GenerateConstructor47(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor46(__VA_ARGS__))
#define GenerateConstructor48(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor47(__VA_ARGS__))
#define GenerateConstructor49(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor48(__VA_ARGS__))
#define GenerateConstructor50(type, name, ...) GenerateConstructor1(type, name), ExpandVAArgs(GenerateConstructor49(__VA_ARGS__))

#define GenerateConstructor(...) ExpandVAArgs(GetGenerator(__VA_ARGS__,\
    GenerateConstructor50, GenerateConstructor50,\
    GenerateConstructor49, GenerateConstructor49,\
    GenerateConstructor48, GenerateConstructor48,\
    GenerateConstructor47, GenerateConstructor47,\
    GenerateConstructor46, GenerateConstructor46,\
    GenerateConstructor45, GenerateConstructor45,\
    GenerateConstructor44, GenerateConstructor44,\
    GenerateConstructor43, GenerateConstructor43,\
    GenerateConstructor42, GenerateConstructor42,\
    GenerateConstructor41, GenerateConstructor41,\
    GenerateConstructor40, GenerateConstructor40,\
    GenerateConstructor39, GenerateConstructor39,\
    GenerateConstructor38, GenerateConstructor38,\
    GenerateConstructor37, GenerateConstructor37,\
    GenerateConstructor36, GenerateConstructor36,\
    GenerateConstructor35, GenerateConstructor35,\
    GenerateConstructor34, GenerateConstructor34,\
    GenerateConstructor33, GenerateConstructor33,\
    GenerateConstructor32, GenerateConstructor32,\
    GenerateConstructor31, GenerateConstructor31,\
    GenerateConstructor30, GenerateConstructor30,\
    GenerateConstructor29, GenerateConstructor29,\
    GenerateConstructor28, GenerateConstructor28,\
    GenerateConstructor27, GenerateConstructor27,\
    GenerateConstructor26, GenerateConstructor26,\
    GenerateConstructor25, GenerateConstructor25,\
    GenerateConstructor24, GenerateConstructor24,\
    GenerateConstructor23, GenerateConstructor23,\
    GenerateConstructor22, GenerateConstructor22,\
    GenerateConstructor21, GenerateConstructor21,\
    GenerateConstructor20, GenerateConstructor20,\
    GenerateConstructor19, GenerateConstructor19,\
    GenerateConstructor18, GenerateConstructor18,\
    GenerateConstructor17, GenerateConstructor17,\
    GenerateConstructor16, GenerateConstructor16,\
    GenerateConstructor15, GenerateConstructor15,\
    GenerateConstructor14, GenerateConstructor14,\
    GenerateConstructor13, GenerateConstructor13,\
    GenerateConstructor12, GenerateConstructor12,\
    GenerateConstructor11, GenerateConstructor11,\
    GenerateConstructor10, GenerateConstructor10,\
    GenerateConstructor9, GenerateConstructor9,\
    GenerateConstructor8, GenerateConstructor8,\
    GenerateConstructor7, GenerateConstructor7,\
    GenerateConstructor6, GenerateConstructor6,\
    GenerateConstructor5, GenerateConstructor5,\
    GenerateConstructor4, GenerateConstructor4,\
    GenerateConstructor3, GenerateConstructor3,\
    GenerateConstructor2, GenerateConstructor2,\
    GenerateConstructor1, GenerateConstructor1)(__VA_ARGS__))

#define GenerateStructElements1(_type, name) {xng::ShaderScript::ShaderTypeOf<_type>::type::TYPE, #name}
#define GenerateStructElements2(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements1(__VA_ARGS__))
#define GenerateStructElements3(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements2(__VA_ARGS__))
#define GenerateStructElements4(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements3(__VA_ARGS__))
#define GenerateStructElements5(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements4(__VA_ARGS__))
#define GenerateStructElements6(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements5(__VA_ARGS__))
#define GenerateStructElements7(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements6(__VA_ARGS__))
#define GenerateStructElements8(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements7(__VA_ARGS__))
#define GenerateStructElements9(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements8(__VA_ARGS__))
#define GenerateStructElements10(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements9(__VA_ARGS__))
#define GenerateStructElements11(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements10(__VA_ARGS__))
#define GenerateStructElements12(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements11(__VA_ARGS__))
#define GenerateStructElements13(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements12(__VA_ARGS__))
#define GenerateStructElements14(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements13(__VA_ARGS__))
#define GenerateStructElements15(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements14(__VA_ARGS__))
#define GenerateStructElements16(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements15(__VA_ARGS__))
#define GenerateStructElements17(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements16(__VA_ARGS__))
#define GenerateStructElements18(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements17(__VA_ARGS__))
#define GenerateStructElements19(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements18(__VA_ARGS__))
#define GenerateStructElements20(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements19(__VA_ARGS__))
#define GenerateStructElements21(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements20(__VA_ARGS__))
#define GenerateStructElements22(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements21(__VA_ARGS__))
#define GenerateStructElements23(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements22(__VA_ARGS__))
#define GenerateStructElements24(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements23(__VA_ARGS__))
#define GenerateStructElements25(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements24(__VA_ARGS__))
#define GenerateStructElements26(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements25(__VA_ARGS__))
#define GenerateStructElements27(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements26(__VA_ARGS__))
#define GenerateStructElements28(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements27(__VA_ARGS__))
#define GenerateStructElements29(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements28(__VA_ARGS__))
#define GenerateStructElements30(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements29(__VA_ARGS__))
#define GenerateStructElements31(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements30(__VA_ARGS__))
#define GenerateStructElements32(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements31(__VA_ARGS__))
#define GenerateStructElements33(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements32(__VA_ARGS__))
#define GenerateStructElements34(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements33(__VA_ARGS__))
#define GenerateStructElements35(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements34(__VA_ARGS__))
#define GenerateStructElements36(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements35(__VA_ARGS__))
#define GenerateStructElements37(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements36(__VA_ARGS__))
#define GenerateStructElements38(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements37(__VA_ARGS__))
#define GenerateStructElements39(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements38(__VA_ARGS__))
#define GenerateStructElements40(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements39(__VA_ARGS__))
#define GenerateStructElements41(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements40(__VA_ARGS__))
#define GenerateStructElements42(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements41(__VA_ARGS__))
#define GenerateStructElements43(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements42(__VA_ARGS__))
#define GenerateStructElements44(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements43(__VA_ARGS__))
#define GenerateStructElements45(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements44(__VA_ARGS__))
#define GenerateStructElements46(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements45(__VA_ARGS__))
#define GenerateStructElements47(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements46(__VA_ARGS__))
#define GenerateStructElements48(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements47(__VA_ARGS__))
#define GenerateStructElements49(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements48(__VA_ARGS__))
#define GenerateStructElements50(type, name, ...) GenerateStructElements1(type, name), ExpandVAArgs(GenerateStructElements49(__VA_ARGS__))

#define GenerateStructElements(...) ExpandVAArgs(GetGenerator(__VA_ARGS__,\
    GenerateStructElements50, GenerateStructElements50, \
    GenerateStructElements49, GenerateStructElements49, \
    GenerateStructElements48, GenerateStructElements48, \
    GenerateStructElements47, GenerateStructElements47, \
    GenerateStructElements46, GenerateStructElements46, \
    GenerateStructElements45, GenerateStructElements45, \
    GenerateStructElements44, GenerateStructElements44, \
    GenerateStructElements43, GenerateStructElements43, \
    GenerateStructElements42, GenerateStructElements42, \
    GenerateStructElements41, GenerateStructElements41, \
    GenerateStructElements40, GenerateStructElements40, \
    GenerateStructElements39, GenerateStructElements39, \
    GenerateStructElements38, GenerateStructElements38, \
    GenerateStructElements37, GenerateStructElements37, \
    GenerateStructElements36, GenerateStructElements36, \
    GenerateStructElements35, GenerateStructElements35, \
    GenerateStructElements34, GenerateStructElements34, \
    GenerateStructElements33, GenerateStructElements33, \
    GenerateStructElements32, GenerateStructElements32, \
    GenerateStructElements31, GenerateStructElements31, \
    GenerateStructElements30, GenerateStructElements30, \
    GenerateStructElements29, GenerateStructElements29, \
    GenerateStructElements28, GenerateStructElements28, \
    GenerateStructElements27, GenerateStructElements27, \
    GenerateStructElements26, GenerateStructElements26, \
    GenerateStructElements25, GenerateStructElements25, \
    GenerateStructElements24, GenerateStructElements24, \
    GenerateStructElements23, GenerateStructElements23, \
    GenerateStructElements22, GenerateStructElements22, \
    GenerateStructElements21, GenerateStructElements21, \
    GenerateStructElements20, GenerateStructElements20, \
    GenerateStructElements19, GenerateStructElements19, \
    GenerateStructElements18, GenerateStructElements18, \
    GenerateStructElements17, GenerateStructElements17, \
    GenerateStructElements16, GenerateStructElements16, \
    GenerateStructElements15, GenerateStructElements15, \
    GenerateStructElements14, GenerateStructElements14, \
    GenerateStructElements13, GenerateStructElements13, \
    GenerateStructElements12, GenerateStructElements12, \
    GenerateStructElements11, GenerateStructElements11, \
    GenerateStructElements10, GenerateStructElements10, \
    GenerateStructElements9, GenerateStructElements9, \
    GenerateStructElements8, GenerateStructElements8, \
    GenerateStructElements7, GenerateStructElements7, \
    GenerateStructElements6, GenerateStructElements6, \
    GenerateStructElements5, GenerateStructElements5, \
    GenerateStructElements4, GenerateStructElements4, \
    GenerateStructElements3, GenerateStructElements3, \
    GenerateStructElements2, GenerateStructElements2, \
    GenerateStructElements1, GenerateStructElements1,)(__VA_ARGS__))

#define GenerateCpuElementDeclaration1(type, name) xng::ShaderScript::ShaderCpuType<type> name;
#define GenerateCpuElementDeclaration2(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration1(__VA_ARGS__))
#define GenerateCpuElementDeclaration3(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration2(__VA_ARGS__))
#define GenerateCpuElementDeclaration4(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration3(__VA_ARGS__))
#define GenerateCpuElementDeclaration5(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration4(__VA_ARGS__))
#define GenerateCpuElementDeclaration6(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration5(__VA_ARGS__))
#define GenerateCpuElementDeclaration7(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration6(__VA_ARGS__))
#define GenerateCpuElementDeclaration8(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration7(__VA_ARGS__))
#define GenerateCpuElementDeclaration9(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration8(__VA_ARGS__))
#define GenerateCpuElementDeclaration10(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration9(__VA_ARGS__))
#define GenerateCpuElementDeclaration11(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration10(__VA_ARGS__))
#define GenerateCpuElementDeclaration12(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration11(__VA_ARGS__))
#define GenerateCpuElementDeclaration13(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration12(__VA_ARGS__))
#define GenerateCpuElementDeclaration14(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration13(__VA_ARGS__))
#define GenerateCpuElementDeclaration15(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration14(__VA_ARGS__))
#define GenerateCpuElementDeclaration16(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration15(__VA_ARGS__))
#define GenerateCpuElementDeclaration17(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration16(__VA_ARGS__))
#define GenerateCpuElementDeclaration18(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration17(__VA_ARGS__))
#define GenerateCpuElementDeclaration19(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration18(__VA_ARGS__))
#define GenerateCpuElementDeclaration20(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration19(__VA_ARGS__))
#define GenerateCpuElementDeclaration21(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration20(__VA_ARGS__))
#define GenerateCpuElementDeclaration22(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration21(__VA_ARGS__))
#define GenerateCpuElementDeclaration23(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration22(__VA_ARGS__))
#define GenerateCpuElementDeclaration24(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration23(__VA_ARGS__))
#define GenerateCpuElementDeclaration25(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration24(__VA_ARGS__))
#define GenerateCpuElementDeclaration26(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration25(__VA_ARGS__))
#define GenerateCpuElementDeclaration27(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration26(__VA_ARGS__))
#define GenerateCpuElementDeclaration28(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration27(__VA_ARGS__))
#define GenerateCpuElementDeclaration29(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration28(__VA_ARGS__))
#define GenerateCpuElementDeclaration30(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration29(__VA_ARGS__))
#define GenerateCpuElementDeclaration31(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration30(__VA_ARGS__))
#define GenerateCpuElementDeclaration32(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration31(__VA_ARGS__))
#define GenerateCpuElementDeclaration33(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration32(__VA_ARGS__))
#define GenerateCpuElementDeclaration34(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration33(__VA_ARGS__))
#define GenerateCpuElementDeclaration35(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration34(__VA_ARGS__))
#define GenerateCpuElementDeclaration36(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration35(__VA_ARGS__))
#define GenerateCpuElementDeclaration37(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration36(__VA_ARGS__))
#define GenerateCpuElementDeclaration38(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration37(__VA_ARGS__))
#define GenerateCpuElementDeclaration39(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration38(__VA_ARGS__))
#define GenerateCpuElementDeclaration40(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration39(__VA_ARGS__))
#define GenerateCpuElementDeclaration41(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration40(__VA_ARGS__))
#define GenerateCpuElementDeclaration42(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration41(__VA_ARGS__))
#define GenerateCpuElementDeclaration43(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration42(__VA_ARGS__))
#define GenerateCpuElementDeclaration44(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration43(__VA_ARGS__))
#define GenerateCpuElementDeclaration45(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration44(__VA_ARGS__))
#define GenerateCpuElementDeclaration46(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration45(__VA_ARGS__))
#define GenerateCpuElementDeclaration47(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration46(__VA_ARGS__))
#define GenerateCpuElementDeclaration48(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration47(__VA_ARGS__))
#define GenerateCpuElementDeclaration49(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration48(__VA_ARGS__))
#define GenerateCpuElementDeclaration50(type, name, ...) GenerateCpuElementDeclaration1(type, name) ExpandVAArgs(GenerateCpuElementDeclaration49(__VA_ARGS__))

#define GenerateCpuElementDeclaration(...) ExpandVAArgs(GetGenerator(__VA_ARGS__,\
    GenerateCpuElementDeclaration50, GenerateCpuElementDeclaration50,\
    GenerateCpuElementDeclaration49, GenerateCpuElementDeclaration49,\
    GenerateCpuElementDeclaration48, GenerateCpuElementDeclaration48,\
    GenerateCpuElementDeclaration47, GenerateCpuElementDeclaration47,\
    GenerateCpuElementDeclaration46, GenerateCpuElementDeclaration46,\
    GenerateCpuElementDeclaration45, GenerateCpuElementDeclaration45,\
    GenerateCpuElementDeclaration44, GenerateCpuElementDeclaration44,\
    GenerateCpuElementDeclaration43, GenerateCpuElementDeclaration43,\
    GenerateCpuElementDeclaration42, GenerateCpuElementDeclaration42,\
    GenerateCpuElementDeclaration41, GenerateCpuElementDeclaration41,\
    GenerateCpuElementDeclaration40, GenerateCpuElementDeclaration40,\
    GenerateCpuElementDeclaration39, GenerateCpuElementDeclaration39,\
    GenerateCpuElementDeclaration38, GenerateCpuElementDeclaration38,\
    GenerateCpuElementDeclaration37, GenerateCpuElementDeclaration37,\
    GenerateCpuElementDeclaration36, GenerateCpuElementDeclaration36,\
    GenerateCpuElementDeclaration35, GenerateCpuElementDeclaration35,\
    GenerateCpuElementDeclaration34, GenerateCpuElementDeclaration34,\
    GenerateCpuElementDeclaration33, GenerateCpuElementDeclaration33,\
    GenerateCpuElementDeclaration32, GenerateCpuElementDeclaration32,\
    GenerateCpuElementDeclaration31, GenerateCpuElementDeclaration31,\
    GenerateCpuElementDeclaration30, GenerateCpuElementDeclaration30,\
    GenerateCpuElementDeclaration29, GenerateCpuElementDeclaration29,\
    GenerateCpuElementDeclaration28, GenerateCpuElementDeclaration28,\
    GenerateCpuElementDeclaration27, GenerateCpuElementDeclaration27,\
    GenerateCpuElementDeclaration26, GenerateCpuElementDeclaration26,\
    GenerateCpuElementDeclaration25, GenerateCpuElementDeclaration25,\
    GenerateCpuElementDeclaration24, GenerateCpuElementDeclaration24,\
    GenerateCpuElementDeclaration23, GenerateCpuElementDeclaration23,\
    GenerateCpuElementDeclaration22, GenerateCpuElementDeclaration22,\
    GenerateCpuElementDeclaration21, GenerateCpuElementDeclaration21,\
    GenerateCpuElementDeclaration20, GenerateCpuElementDeclaration20,\
    GenerateCpuElementDeclaration19, GenerateCpuElementDeclaration19,\
    GenerateCpuElementDeclaration18, GenerateCpuElementDeclaration18,\
    GenerateCpuElementDeclaration17, GenerateCpuElementDeclaration17,\
    GenerateCpuElementDeclaration16, GenerateCpuElementDeclaration16,\
    GenerateCpuElementDeclaration15, GenerateCpuElementDeclaration15,\
    GenerateCpuElementDeclaration14, GenerateCpuElementDeclaration14,\
    GenerateCpuElementDeclaration13, GenerateCpuElementDeclaration13,\
    GenerateCpuElementDeclaration12, GenerateCpuElementDeclaration12,\
    GenerateCpuElementDeclaration11, GenerateCpuElementDeclaration11,\
    GenerateCpuElementDeclaration10, GenerateCpuElementDeclaration10,\
    GenerateCpuElementDeclaration9, GenerateCpuElementDeclaration9,\
    GenerateCpuElementDeclaration8, GenerateCpuElementDeclaration8,\
    GenerateCpuElementDeclaration7, GenerateCpuElementDeclaration7,\
    GenerateCpuElementDeclaration6, GenerateCpuElementDeclaration6,\
    GenerateCpuElementDeclaration5, GenerateCpuElementDeclaration5,\
    GenerateCpuElementDeclaration4, GenerateCpuElementDeclaration4,\
    GenerateCpuElementDeclaration3, GenerateCpuElementDeclaration3,\
    GenerateCpuElementDeclaration2, GenerateCpuElementDeclaration2,\
    GenerateCpuElementDeclaration1, GenerateCpuElementDeclaration1)(__VA_ARGS__))

/**
 *  This macro creates a C++ struct containing the specified member type/name pairs in the var args.
 *  The struct acts as a wrapper around ShaderObject for accessing members of a ShaderStructObject instance through named c++ members.
 *
 *  The macro also defines a nested CPU struct (accessible as name::CPU) with the same
 *  member type/name pairs for easier data management on the cpu side for shader buffer types.
 *
 *  The name::CPU type can be directly used as the cpu side representation
 *  of the shader struct without worrying about padding and alignment.
 *
 *  Object nesting is supported.
 *  Up to 50 member variables are supported.
 *
 *  The getShaderStruct() public static function can be used to retrieve the ShaderStructDef instance.
 *
 *  e.g.:
 *      DefineStruct(MvpBuffer, Mat4f, mvp)
 *
 *      void shader() {
 *          ...
 *          MvpBuffer myBuffer;
 *          myBuffer.mvp = mat4();
 *      }
 *
 * @param name The type name of the struct
 */
#define ShaderStruct(name, ...)\
    struct name {\
        static constexpr char _##name##_type[] = #name;\
        struct CPU {\
            GenerateCpuElementDeclaration(__VA_ARGS__)\
        };\
        static inline xng::ShaderDataType TYPE{static_cast<xng::ShaderStructType>(#name), 1};\
        static xng::ShaderStructDef getShaderStructDef() {\
            return xng::ShaderStructDef(#name, {\
                GenerateStructElements(__VA_ARGS__) \
            });\
        }\
        xng::ShaderScript::ShaderObject _object;\
        GenerateElementDeclaration(__VA_ARGS__)\
        name() : _object(xng::ShaderScript::ShaderStructObject<_##name##_type, 1>()), GenerateConstructor(__VA_ARGS__) { xng::ShaderScript::ShaderScope::get().addTypeDefinition(getShaderStructDef()); }\
        name(const xng::ShaderScript::ShaderObject &buffer, bool b = false) : _object(buffer), GenerateConstructor(__VA_ARGS__) { xng::ShaderScript::ShaderScope::get().addTypeDefinition(getShaderStructDef()); }\
        name& operator=(const name& other) {\
            _object = other._object;\
            return *this;\
        }\
        name& operator=(const xng::ShaderScript::ShaderObject& other) {\
            _object = other;\
            return *this;\
        }\
        operator const xng::ShaderScript::ShaderObject&() const { return _object; }\
    };

#endif //XENGINE_RENDERGRAPH_SHADERSTRUCT_HPP
