/**
 *  This file is part of xEngine, a C++ game engine library.
 *  Copyright (C) 2023  Julian Zampiccoli
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License along
 *  with this program; if not, write to the Free Software Foundation, Inc.,
 *  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#include "xng/driver/driver.hpp"

#include <map>

#include "compiled_drivers.h" // This header is generated by cmake/drivers.cmake

namespace xng {
    const std::map<std::string, Driver::Creator> &getDrivers() {
        return DriverGenerator::getDrivers();
    }

    std::unique_ptr<Driver> Driver::load(const std::string &name) {
        auto &drivers = getDrivers();
        auto it = drivers.find(name);
        if (it == drivers.end()){
            throw std::runtime_error("No driver with name " + name + " found.");
        }
        return it->second();
    }
}