/**
 *  This file is part of xEngine, a C++ game engine library.
 *  Copyright (C) 2022  Julian Zampiccoli
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License along
 *  with this program; if not, write to the Free Software Foundation, Inc.,
 *  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#include "xng/driver/driverloader.hpp"

#include <stdexcept>
#include <utility>

#include "compiled_drivers.h" // The header file generated by drivers.cmake containing the DriverGenerator::setup() definition which adds the compiled drivers to the map of drivers.

namespace xng {
    static bool driversInitialized = false;
    static std::map<std::type_index, std::map<std::string, DriverLoader::DriverCreator>> drivers;

    std::map<std::type_index, std::map<std::string, DriverLoader::DriverCreator>> &DriverLoader::getDriversInstance() {
        if (!driversInitialized) {
            driversInitialized = true;
            DriverGenerator::setup(drivers);
        }
        return drivers;
    }
}