/**
 *   xEngine - C++ Game Engine Library
 *   Copyright (C) 2026 Julia Zampiccoli
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   Lesser General Public License for more details.
 *
 *   You should have received a copy of the Lesser General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef XENGINE_SHADERTYPE_HPP
#define XENGINE_SHADERTYPE_HPP

#include "xng/rendergraph/shader/shaderprimitive.hpp"
#include "xng/shaderscript/shaderobject.hpp"
#include "xng/shaderscript/std140.hpp"

/**
 * Template-based type conversion from c++ type to ShaderPrimitive
 */
namespace xng::ShaderScript {
    // Maps a C++ scalar type to the corresponding rg::ShaderPrimitiveType::Component enum value.
    template<typename T>
    struct ShaderComponentOf;

    template<>
    struct ShaderComponentOf<bool> {
        static constexpr rg::ShaderPrimitiveType::Component value = rg::ShaderPrimitiveType::BOOLEAN;
    };

    template<>
    struct ShaderComponentOf<int> {
        static constexpr rg::ShaderPrimitiveType::Component value = rg::ShaderPrimitiveType::SIGNED_INT;
    };

    template<>
    struct ShaderComponentOf<unsigned int> {
        static constexpr rg::ShaderPrimitiveType::Component value = rg::ShaderPrimitiveType::UNSIGNED_INT;
    };

    template<>
    struct ShaderComponentOf<float> {
        static constexpr rg::ShaderPrimitiveType::Component value = rg::ShaderPrimitiveType::FLOAT;
    };

    template<>
    struct ShaderComponentOf<double> {
        static constexpr rg::ShaderPrimitiveType::Component value = rg::ShaderPrimitiveType::DOUBLE;
    };

    // Extracts template parameters from a ShaderDataObject instantiation.
    template<typename T>
    struct ShaderDataObjectTraits;

    template<rg::ShaderPrimitiveType::Type TYPE, rg::ShaderPrimitiveType::Component COMP, size_t C>
    struct ShaderDataObjectTraits<ShaderDataObject<TYPE, COMP, C> > {
        static constexpr rg::ShaderPrimitiveType::Type value_type = TYPE;
        static constexpr rg::ShaderPrimitiveType::Component component = COMP;
        static constexpr size_t count = C;
    };

    // Maps a C++ math type to its DSL ShaderDataObject type.
    // Primary: undefined (compile error for unsupported types).
    // DSL struct types (generated by DefineStruct) expose a nested CPU type
    // and are detected by the partial specialization below — they ARE their own DSL type.
    template<typename T, typename = void>
    struct ShaderTypeOf;

    template<>
    struct ShaderTypeOf<bool> {
        using type = ShaderDataObject<rg::ShaderPrimitiveType::SCALAR, rg::ShaderPrimitiveType::BOOLEAN, 1>;
    };

    template<>
    struct ShaderTypeOf<int> {
        using type = ShaderDataObject<rg::ShaderPrimitiveType::SCALAR, rg::ShaderPrimitiveType::SIGNED_INT, 1>;
    };

    template<>
    struct ShaderTypeOf<unsigned int> {
        using type = ShaderDataObject<rg::ShaderPrimitiveType::SCALAR, rg::ShaderPrimitiveType::UNSIGNED_INT, 1>;
    };

    template<>
    struct ShaderTypeOf<float> {
        using type = ShaderDataObject<rg::ShaderPrimitiveType::SCALAR, rg::ShaderPrimitiveType::FLOAT, 1>;
    };

    template<>
    struct ShaderTypeOf<double> {
        using type = ShaderDataObject<rg::ShaderPrimitiveType::SCALAR, rg::ShaderPrimitiveType::DOUBLE, 1>;
    };

    template<typename T>
    struct ShaderTypeOf<Vector2<T> > {
        using type = ShaderDataObject<rg::ShaderPrimitiveType::VECTOR2, ShaderComponentOf<T>::value, 1>;
    };

    template<typename T>
    struct ShaderTypeOf<Vector3<T> > {
        using type = ShaderDataObject<rg::ShaderPrimitiveType::VECTOR3, ShaderComponentOf<T>::value, 1>;
    };

    template<typename T>
    struct ShaderTypeOf<Vector4<T> > {
        using type = ShaderDataObject<rg::ShaderPrimitiveType::VECTOR4, ShaderComponentOf<T>::value, 1>;
    };

    template<typename T>
    struct ShaderTypeOf<Matrix<T, 2, 2> > {
        using type = ShaderDataObject<rg::ShaderPrimitiveType::MAT2, ShaderComponentOf<T>::value, 1>;
    };

    template<typename T>
    struct ShaderTypeOf<Matrix<T, 3, 3> > {
        using type = ShaderDataObject<rg::ShaderPrimitiveType::MAT3, ShaderComponentOf<T>::value, 1>;
    };

    template<typename T>
    struct ShaderTypeOf<Matrix<T, 4, 4> > {
        using type = ShaderDataObject<rg::ShaderPrimitiveType::MAT4, ShaderComponentOf<T>::value, 1>;
    };

    template<typename T, size_t N>
    struct ShaderTypeOf<std::array<T, N> > {
    private:
        using traits = ShaderDataObjectTraits<typename ShaderTypeOf<T>::type>;

    public:
        using type = ShaderDataObject<traits::value_type, traits::component, (int) N>;
    };

    // DSL struct types: detected by presence of nested T::CPU.
    // The struct itself IS the DSL type — no wrapping needed.
    template<typename T>
    struct ShaderTypeOf<T, std::void_t<typename T::CPU> > {
        using type = T;
    };

    template<typename T, typename = void>
    struct ShaderCpuTypeOf {
        using type = Std140<T>;
    };

    template<typename T>
    struct ShaderCpuTypeOf<T, std::void_t<typename T::CPU> > {
        using type = typename T::CPU;
    };

    template<typename T>
    using ShaderType = typename ShaderCpuTypeOf<T>::type;
}

#endif //XENGINE_SHADERTYPE_HPP
