set(CMAKE_SYSTEM_NAME Android)
set(CMAKE_ANDROID_ARCH_ABI armeabi-v7a)

include(${CMAKE_CURRENT_LIST_DIR}/user-config-toolchain.cmake)

if(USER_CONF_ANDROID_SYSTEM_VERSION)
    set(CMAKE_SYSTEM_VERSION ${USER_CONF_ANDROID_SYSTEM_VERSION})
endif()

if(USER_CONF_ANDROID_NDK)
    set(CMAKE_ANDROID_NDK ${USER_CONF_ANDROID_NDK})
endif()

if (USER_CONF_ANDROID_STL_TYPE)
    set(CMAKE_ANDROID_STL_TYPE ${USER_CONF_ANDROID_STL_TYPE})
endif()
