/**
 *   xEngine - C++ Game Engine Library
 *   Copyright (C) 2026 Julia Zampiccoli
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   Lesser General Public License for more details.
 *
 *   You should have received a copy of the Lesser General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef XENGINE_SHADERTYPES_HPP
#define XENGINE_SHADERTYPES_HPP

#include "xng/shaderscript/macro/shaderstruct.hpp"

namespace xng {
    ShaderStruct(ShaderCamera,
                 Vec4f, viewPosition,
                 Mat4f, view,
                 Mat4f, projection)

    ShaderStruct(ShaderTransform,
                 Mat4f, transform)

    using Mat4f_Array_6 = std::array<Mat4f, 6>;

    ShaderStruct(ShaderPointLight,
                 Vec4f, position,
                 Vec4f, color,
                 Vec4f, shadowFarPlane,
                 Mat4f_Array_6, shadowMatrices)

    ShaderStruct(ShaderDirectionalLight,
                 Vec4f, color,
                 Vec4f, direction,
                 Vec4f, shadowFarPlane,
                 Mat4f, shadowProjectionMatrix)

    ShaderStruct(ShaderSpotLight,
                 Vec4f, position,
                 Vec4f, color,
                 Vec4f, direction_quadratic,
                 Vec4f, cutOff_outerCutOff_constant_linear,
                 Vec4f, shadowFarPlane,
                 Mat4f, shadowProjectionMatrix)

    ShaderStruct(ShaderTexture,
                 Vec2i, level_index,
                 Vec4i, minFilter_magFilter_mipFilter_wrap,
                 Vec4f, scale_texSize)

    ShaderStruct(ShaderMaterial,
                 Vec4f, albedoColor,
                 Vec4f, metallic_roughness_ambientOcclusion,
                 Vec4f, normalIntensity,
                 ShaderTexture, normal,
                 ShaderTexture, metallic,
                 ShaderTexture, roughness,
                 ShaderTexture, ambientOcclusion,
                 ShaderTexture, albedo)

    /**
     * Indexed by the pre pass to build the ShaderDrawMesh list.
     */
    ShaderStruct(ShaderMesh,
                 int, baseVertex,
                 unsigned int, indexOffset, // The first index
                 unsigned int, indexCount,
                 int, modelID, // The ID of the RenderModel object
                 int, meshID, // The ID of the RenderMesh object
                 int, transformIndex,
                 int, materialIndex,
                 bool, receiveShadows)

    /**
     * Generated by the pre pass, indexed via indirect draw
     */
    ShaderStruct(ShaderDrawMesh,
                 Mat4f, mvp,
                 int, modelID,
                 int, meshID,
                 int, transformIndex,
                 int, materialIndex,
                 bool, receiveShadows)

    ShaderStruct(ShaderCanvasPaint,
                 Vec4f, color,
                 float, colorMixFactor,
                 float, alphaMixFactor,
                 Vec4f, uvOffset_uvScale,
                 ShaderTexture, texture)

    ShaderStruct(ShaderConfiguration,
                 Vec4f, gamma)
}

#endif //XENGINE_SHADERTYPES_HPP
